### ISSUE TITLE
position of terminal is fixed, xterm selection's position is wrong

### ISSUE THREAD

**Issue by GavinSong123** [xtermjs/xterm.js#1132]
When terminal container's position is fixed and page has a lot of contents. If I scroll page, the selection of xterm is wrong and content can not be copied.

## Details
- Browser and browser version: chrome Version 51.0.2704.84 (64-bit)
- OS version: ubuntu 16.04
- xterm.js version: 2.9.2

### Steps to reproduce

1. 
![image](https://user-images.githubusercontent.com/14323101/33066223-b3e6a824-cee5-11e7-995d-c1395c2f4779.png)

2. If I scroll the page, the selection's position is wrong.
![image](https://user-images.githubusercontent.com/14323101/33066281-d51a47da-cee5-11e7-9315-cf888edcf124.png)

**Comment by mofux** [comment]
That happens because `position: fixed` is not currently supported. Here is the code that probably needs to get modified in order to support it: https://github.com/xtermjs/xterm.js/blob/v3/src/utils/MouseHelper.ts#L24-L34

However, using `position: fixed` on the terminal doesn't seem to be a good idea in general. You should rethink your application layout and try to avoid using it. I guess your use-case is something like a drop-in terminal that always stays in one edge and overlays the content behind? You could achieve the same with a layout like this (which should be supported by xterm.js):

```html
<body>
  <div id="content" style="width: 100%; height: 100%; overflow-y: auto">
    ... my scrollable content ...
  </div>
  <div id="terminal" style="position: absolute; bottom: 0; left: 0; right: 0">
     ... terminal goes here ...
  </div>
</body>
```

**Comment by GavinSong123** [comment]
@mofux If I using `position: absolute`  on the terminal, terminal will be scrolled with page. It can not make the terminal always stays in one edge.

**Comment by mofux** [comment]
@GavinSong123 I've build a more complete example here: https://jsfiddle.net/26crb93g/

**Comment by Tyriar** [comment]
I'm assuming this was fixed in v3
