### ISSUE TITLE
Handle terminal.open on an element that is not (yet) attached to the dom

### ISSUE THREAD

**Issue by mofux** [xtermjs/xterm.js#1158]
At the moment, `terminal.open(parentElement)` has to be called on a HTMLElement that is already attached to the DOM. If the element is not attached, we will fail silently (blank terminal - no errors). We should either check and warn if `term.open` is called on an unattached element, or preferably (if supported) use a MutationObserver to defer the open until the parent element is attached.

**Comment by Tyriar** [comment]
Maybe we should fail hard here instead? The reason I think this is a better option is because consumers should not be opening until the terminal is ready to be displayed, otherwise we would be encouraging calling open when the terminals are being displayed, wasting cycles (particularly on browsers where `IntersectionObserver` isn't supported).

**Comment by vincentwoo** [comment]
I would like to register a vote for maximum compatibility and letting the user worry about perf. I am running into problems with xterm when opened on a hidden element, etc.

**Comment by Tyriar** [comment]
For anyone who wants to help with this, it could be tackled incrementally if some cases are easier than others.

**Comment by gpetrov** [comment]
Can we check that open failed initially and do a re-open well the element becomes visible?
