### ISSUE TITLE
Importing addons with the new version ???

### ISSUE THREAD

**Issue by Kalen66100** [xtermjs/xterm.js#1272]
## Details
- Browser and browser version:  Chrome 64 
- OS version: Ubuntu 64 bits
- xterm.js version: 3.0.2

I'm trying the new version of xterm.js and I'm stuck on the way to import addons.

This is what I do in my main.js :
```javascript
import * as Terminal from './xterm';
import * as attach from './addons/attach/attach';
import * as fit from './addons/fit/fit';
import * as fullscreen from './addons/fullscreen/fullscreen';
import * as search from './addons/search/search';
import * as winptyCompat from './addons/winptyCompat/winptyCompat';

Terminal.applyAddon(attach);
Terminal.applyAddon(fit);
Terminal.applyAddon(fullscreen);
Terminal.applyAddon(search);
Terminal.applyAddon(winptyCompat);
```
On the navigator I have this error: 
**Uncaught SyntaxError: Unexpected token ***

I don't really know how to use this new system, can someone help me ?

**Comment by parisk** [comment]
Thanks for reporting @Kalen66100. Can you provide us with a screenshot from your console displaying this log?

We need to see the corresponding file and its line that raises this error.

Also, are you running the above code as-is in Chrome or are you compiling it to a compatible format with a tool like Webpack? (The above code cannot run on its own in any browser by default).

**Comment by Kalen66100** [comment]
As the old demo, I'm running it in Chrome, no webpack. How can  I compile it ?
The project where xterm.js is integrated is in GWT and I'm using wildfly to host the website.
Thanks,

**Comment by parisk** [comment]
@Kalen66100 starting with xterm.js 3 the demo is being bundled with Webpack, so the `import` statements can be converted to browser compatible JavaScript.

To be honest, I do not quite understand your project's structure and I have no experience with either GWT or Wildfly.

I propose you to take a look at the following, which might help:

1. Webpack configuration for the demo:
 https://github.com/xtermjs/xterm.js/blob/master/webpack.config.js
2. Gulp task for running the Webpack build: https://github.com/xtermjs/xterm.js/blob/master/gulpfile.js#L189
3. Run the demo: https://github.com/xtermjs/xterm.js#demo
4. See the output bundle at `demo/dist`
5. Try to replicate the above flow for your application

For a dedicated xterm.js-webpack example you can take a look at https://github.com/parisk/xterm-webpack.

---

I will be closing this issue, since there are no known issues with importing xterm.js or its add-ons.

If there are still questions about integrating xterm.js in your application, the best place to ask them is the StackOverflow tag `xtermjs`: https://stackoverflow.com/tags/xtermjs.
