### ISSUE TITLE
Incorrect color is used for bold fonts

### ISSUE THREAD

**Issue by mofux** [xtermjs/xterm.js#1342]
If a bold character is drawn we are changing its color to use the light variant of it (colors.ansi[color + 8]) which seems wrong to me.

https://github.com/xtermjs/xterm.js/blob/master/src/renderer/TextRenderLayer.ts#L167-L173

@Tyriar Is this by spec or by mistake?

**Comment by egmontkob** [comment]
This is an often seen traditional behavior. ECMA-48 says "bold or increased intensity". Most terminal emulators switch to bold and the brighter counterpart of the color at the same time. This, however, only happens if the legacy (SGR 30-37) escape sequences were used to select the color; if the same base color was selected using the 256-color escape sequences (SGR 38;5;0-7) then the bold attribute doesn't switch to the brighter column in any of the emulators I've tried (which list doesn't include xterm.js :P, I'm not sure about that).

With the generic availability of 256 colors (and sometimes even 16M true colors), this behavior is sure rather a legacy than something that makes too much sense. Technically it's much better to keep boldness and the color independent, and is also essential for color schemes like Solarized. Some terminal emulators have an option for this behavior, e.g. `xterm +pc`, `urxvt +is`. In brand new vte-0.52/gnome-terminal-3.28 we also started moving in this direction of clearly separating these two things, see [GNOME 762247](https://bugzilla.gnome.org/show_bug.cgi?id=762247) (especially comments 1 & 14) for details. See also [Kitty 135](https://github.com/kovidgoyal/kitty/issues/135) for Kitty author's matching opinion.

And for some more far-fetched (although still pretty much related) thoughts from me see also [GNOME 791596](https://bugzilla.gnome.org/show_bug.cgi?id=791596) (esp. comment 1).

If you're brave enough, you can just disable this behavior and see how many people complain that suddenly the colors of their utilities don't look nice. I'd be curious to see. :) I wasn't this brave in VTE to flip the default.

**Comment by ztmr** [comment]
Related to #1239.

**Comment by egmontkob** [comment]
Haha, I totally forgot there was already a similar bug and that I had already commented on that :)

**Comment by Tyriar** [comment]
Let's close this off in favor of #1239

**Comment by Tyriar** [comment]
Looks like macOS' default terminal disables this by default now:

<img width="221" alt="Screen Shot 2019-04-30 at 12 44 40 PM" src="https://user-images.githubusercontent.com/2193314/56988868-e62af080-6b45-11e9-993a-0f9a1749f157.png">

I'm quite sure I didn't change this myself.
