### ISSUE TITLE
Pasted newline not displayed as newline

### ISSUE THREAD

**Issue by kaofishy** [xtermjs/xterm.js#1382]
When pasting data with newline through the terminal and looping the same data back to be displayed, the terminal does not display the newline as expected.

## Details
- Browser and browser version: Chrome 61 (Electron 2.0 beta)
- OS version: Windows 
- xterm.js version: 3.2.0

### Steps to reproduce

1. Send data with newline through the terminal
2. Display looped back data

Sample code:
```javascript
term.on('data', (data) => {
  term.write(data);
})
```

**Comment by Tyriar** [comment]
I think this is because all new lines are normalized to `\r` (`0x0D`) when pasted which is what shells expect, but xterm.js needs an actual line feed character `\n` (`0x0A`). A carriage return should move the cursor to the first column:

https://github.com/xtermjs/xterm.js/blob/989f5873f574125a917be32267c8d633f0a09659/src/InputHandler.ts#L150-L152

Try something like this:

```
term.on('data', (data) => {
  term.write(data.replace(/\r/g, '\n\r');
})
```
