### ISSUE TITLE
Same code returns different results

### ISSUE THREAD

**Issue by mimarec** [xtermjs/xterm.js#1498]
The same code returns different results, depending on where the node application is run

## Details
- Browser and browser version:  Chrome Version 66.0.3359.181 (Build oficial) (64 bits)
- OS version: OS X El Capitan v10.11.6
- xterm.js version: 3.4.1

I'm having a behavior that I do not understand, the demo application opens with different information as you launch the process from one place or another:

1) Execute the npm start command from the command line (MacOSX Terminal) and the result obtained is as follows:

<img width="863" alt="captura de pantalla 2018-06-07 a las 11 27 02" src="https://user-images.githubusercontent.com/5499914/41091664-5f7c572c-6a47-11e8-87cd-e1c4aa656974.png">

2) Execute the command node app.js (MacOSX Terminal) over the demo folder and the result obtained is as follows:

<img width="991" alt="captura de pantalla 2018-06-07 a las 11 21 34" src="https://user-images.githubusercontent.com/5499914/41091673-66d078b4-6a47-11e8-9ecb-e0258f28e56d.png">

Why are different results obtained and how can I always obtain the second result?

PD: I am sure that this is not an issue but I not understanding the result.
PD2: Sorry for my English

**Comment by mofux** [comment]
The only different in both cases is the current working directory for which the `bash` process is spawned, as you can see here: https://github.com/xtermjs/xterm.js/blob/master/demo/app.js#L35. What happens if you manually run `bash` in the two folders using Terminal.app? Do you see the same difference? This is more of a `node-pty`question and could also be related to your environment.

**Comment by mimarec** [comment]
Thanks, both examples are running from the Terminal.app.
I do not understand, because the command `npm start` prints the name of the interpreter used, while the command `node app.js` prints _my user name_ '@' _the name of the machine_ ':' _the current working directory_.

Yes, it's probably more of a query in the node-pty repo.

Thank you very much! :)

**Comment by theflyingape** [comment]
Yes, node-pty can take specific environment passing to the spawned process, but it also inherits an environment depending on how it's launched, i.e., from a developer's shell as opposed to a systemd service startup.  You can validate the differences using `env` and `echo $PS1`.

**Comment by Tyriar** [comment]
This is related to the environment, there are differences in macOS when you run an application from the terminal (and inherit that environment) or from the dock (and inherit that one). The latter of the two does not run inside a login shell, so unless you run `bash -l` as the shell you will not run `.bash_profile`. You can read more about this here https://apple.stackexchange.com/a/51038

This is as designed but it's a constant cause of frustration for me due to how macOS differs from Linux.

**Comment by mimarec** [comment]
Thanks!
