### ISSUE TITLE
Colors are wrong when running hh

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1591]
`brew install hh`

From left to right: xterm.js, iterm2, terminal.app

<img width="523" alt="screen shot 2018-07-30 at 7 54 22 am" src="https://user-images.githubusercontent.com/2193314/43405059-d7827b2a-93cd-11e8-9d95-4ced207194a4.png">

VSCode issue: https://github.com/Microsoft/vscode/issues/55320

**Comment by mofux** [comment]
Looks like inverted colors are used here. Interestingly, the invert seems to work for the first row (`- HISTORY - view:ranking`), but fails for the second row where we can notice that text is also rendered in bold 🤔I'm wondering if the same happens with the DOM renderer, maybe we are getting the character incorrectly from the CharAtlas...

**Comment by 7PH** [comment]
Interesting, I had the same issue recently.

Happened when there is negative "**\x1b[7m**" plus bold "**\x1b[1m**" enabled.

## reproduce

```javascript
xterm.write("\x1b[0m\x1b[1;1f\x1b[2J\x1b[7m OK \x1b[1m KO")
```

"OK": black on white
"KO": gray on white

## workaround

A work-around which is working in my very specific case is to add this to the configuration:

```javascript
{ theme: { white: 'black' } }
```

did not have the time to look further yet, but using this workaround is not something I like having in my code.

**Comment by 7PH** [comment]
it seems the issue is related to the **drawBoldTextInBrightColors** property since:
- the bug vanishes when using **drawBoldTextInBrightColors: false** in the configuration.
- other options (fontWeightBold, enableBold) have no effect on this issue

after checking the source code, it seems that in [BaseRenderLayout.drawChars](https://github.com/xtermjs/xterm.js/blob/master/src/renderer/BaseRenderLayer.ts#L240):
- because inverted colors are activated, the foreground color is INVERTED_DEFAULT_COLOR (-1)
- the check for making the foreground color bright is 'fg < 8' and it adds 8 to the color to get the bright equivalent. so when there is bold+inverted the foreground color will always be 7 (which is white)

so what happens is that whatever color is used as foreground, the same color will be drawn (7)

```javascript
xterm.write([
    "\x1b[0m", "\x1b[1;1f", "\x1b[2J", // reset
    "A",
    "\x1b[38;92m", // set bright green
    "B", // bright green on black
    "\x1b[1m", // set bold
    "C", // bold bright green on black
    "\x1b[7m", // set inverted
    "D" // white on bright green
].join(""))
```

I think the simplest way of solving this would be to change
```javascript
const drawInBrightColor = terminal.options.drawBoldTextInBrightColors && bold && fg < 8;
```

by
```javascript
const drawInBrightColor = terminal.options.drawBoldTextInBrightColors && bold && fg < 8 && fg !== INVERTED_DEFAULT_COLOR;
```

in [here](https://github.com/xtermjs/xterm.js/blob/master/src/renderer/BaseRenderLayer.ts#L241)

This will disable the "make dark colors bright when bold is enabled" feature when colors are inverted. (tested and working)

Of course, this does not make colors brights when inverted mode is enabled. But I am not even sure what should be done in that case. Since this is "invert mode", should the feature darken the colors instead of make them brighter? 

Another option would be to detect when colors are inverted, and then if the fg color that should be used (i.e. **this._colors.background**) is not dark enough, darken it (or if it is not bright enough, make it brighter?). 

I would say that the feature should be disabled when inverted colors are enabled because it would add complexity to the code for a minor feature in very particular conditions, but honestly I can go for any solution.

What would you think would be best?

**Comment by mofux** [comment]
@7PH Nice investigation! My feeling would also be that going with your provided solution should be efficient to work around this bug.

```javascript
const drawInBrightColor = terminal.options.drawBoldTextInBrightColors && bold && fg < 8 && fg !== INVERTED_DEFAULT_COLOR;
```

Would you like to create a PR for this? 😁

**Comment by 7PH** [comment]
With pleasure, will do it tonight

**Comment by Tyriar** [comment]
Fixed in https://github.com/xtermjs/xterm.js/pull/1599
