### ISSUE TITLE
Links and select word (double click) don't take into account lines that overflow beyond viewport

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#1713]
@alexr00 mentioned an issue she was seeing that is caused by this edge case. Since we don't reflow right now we keep characters on the same line when we resize, instead of discarding them.

Repro:

1. Echo a URL 
2. Resize the columns such that the URL is cut off
3. Hover the link, **the line incorrectly overflows to following row**
4. Double click the word next to the URL and drag over to the URL, **the selection incorrectly overflows to following row**

<img width="522" alt="screen shot 2018-09-28 at 11 18 23 am" src="https://user-images.githubusercontent.com/2193314/46226246-8438ad00-c310-11e8-8c18-903a048f1be9.png">

This will probably be easier to repro on Linux/mac.

**Comment by jerch** [comment]
Imho a test against of `endIndex` against the current `_terminal.cols` in `Buffer.translateBufferLineToString` and trimming the result if `endIndex` overflows should solve this.

**Comment by jerch** [comment]
It seems there are 2 issues linked to this behavior:

1. `Buffer.translateBufferLineToString` reading into "shadowed content" (beyond the current terminal.cols) after shrinking cols - thats what happens in your repro. This can be fixed after #1641 has landed (see https://github.com/xtermjs/xterm.js/issues/1723#issuecomment-427685464).
2. `isWrapped` gets not lifted upon resize - partially linked to #1710 and #1720, discussion in #1723. This behavior would occur on a previously wrapped line after shrinking (like the repro above but with more data).

Both sub issues are somewhat linked to each other in a way, that any code, that tries to unwrap lines (search plugin + `BufferStringIterator`) will get wrong line content from 1. and wrongly merge them because of 2 - which leads to wrong offsets for viewport markers (selection + linkifier).

**Comment by Tyriar** [comment]
We no longer store lines that overflow I believe
