### ISSUE TITLE
CTRL + C in win os not  work

### ISSUE THREAD

**Issue by ofirrifo** [xtermjs/xterm.js#1868]
I have an issue with the CTRL + C in order to copy text from the terminal
in mac the CMD + C work but in windows CTRL + C  not work
I saw this issue was closed >> https://github.com/xtermjs/xterm.js/issues/118
but I'm still can do the paste via the keyboard in windows os

**Comment by Tyriar** [comment]
By default ctrl+c gets sent to the shell as you wouldn't be able to use bash otherwise. To configure this you need to use this API:

https://github.com/xtermjs/xterm.js/blob/4375b3cdb9e36cd2746ff9a101fbeb48f7d0b794/typings/xterm.d.ts#L473-L482

But I don't think you can hook up the keybinding to the copy event.
