### ISSUE TITLE
Add a section with useful terminal resources to README

### ISSUE THREAD

**Issue by mofux** [xtermjs/xterm.js#1913]
I think it would be a good idea to add a section to our readme that links to terminal specifications that we try to adhere to, and manuals that are generally useful for this topic. 

**Terminal Working Group 🤘**
https://gitlab.freedesktop.org/terminal-wg

**Xterm Control Sequences**
https://invisible-island.net/xterm/ctlseqs/ctlseqs.html

**VT Manual**
http://vt100.net

Any other resources worth mentioning?

**Comment by Tyriar** [comment]
Good idea 👍

Should this go in the wiki instead and link to it from the README?

**Comment by jerch** [comment]
Good to see the platform taking place. There are even some ESC sequence tests that we might want to adopt soon and can fix more of those older bugs.
For me README or wiki will work, guess wiki is the better place since its primarily targetting emulator / application devs' needs and less integrators'?

**Comment by Tyriar** [comment]
Created this: https://github.com/xtermjs/xterm.js/wiki/Useful-References, feel free to expand on it
