### ISSUE TITLE
Reflow doesn't work

### ISSUE THREAD

**Issue by svenefftinge** [xtermjs/xterm.js#1941]
I tried to  get the new reflow support (https://github.com/xtermjs/xterm.js/pull/1864) enabled but don't know how. @Tyriar mentioned

> Note that this only works when the TypedArray buffer is enabled.

Could you tell me how to do that?
When automating the resize for the demo it behaves like below:

![xterm-resize](https://user-images.githubusercontent.com/372735/52696779-267bc900-2f70-11e9-8e6b-8c2f8dd54bdd.gif)

Here's the gitpod workspace from the gif to reproduce:

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io#snapshot/0518b2de-8278-461c-89ca-aea20b479755)

**Comment by mofux** [comment]
The pure demo without login to Gitpod can be found here: https://3000-e2881ed9-8762-4946-afe1-48d0f11b255f.ws-eu0.gitpod.io

My guess is that it's happening because the prompt input line is reflowed by the pty itself, and we are putting our reflow mechanism on top, which causes this strange behavior. You can see in the capture that the (real) prompt line is always preserved and correctly reflowed.

If you `ls -alh` inside that terminal, you can see that its output is also correctly reflowed.

@Tyriar Any thoughts?

**Comment by AndrienkoAleksandr** [comment]
> My guess is that it's happening because the prompt input line is reflowed by the pty itself,

@mofux seems You are right:

![xtermnewreflow](https://user-images.githubusercontent.com/6873095/52783605-14c32000-305b-11e9-9525-c89ebde544c6.gif)

**Comment by Tyriar** [comment]
@svenefftinge the typed array buffer is the only option now and it's on by default because of this line in the release notes: "Removed old js array-based buffer implementation"

> My guess is that it's happening because the prompt input line is reflowed by the pty itself

The line containing the cursor remains untouched by reflow, also all other terminals I've looked at act similarly to this when wrapping the prompt line so I think we're behaving correctly. Debouncing resize should also help with this as it will prevent issues around race conditions where the pty size and xterm.js size are out of sync, I added a note to the resize method to call this out:

https://github.com/xtermjs/xterm.js/blob/3.11.0/typings/xterm.d.ts#L445

**Comment by svenefftinge** [comment]
Ok, thanks I will try that.

**Comment by Tyriar** [comment]
Np, @mofux found https://github.com/xtermjs/xterm.js/issues/1944 after discussing this 👌

**Comment by akosyakov** [comment]
It's still an issue in 3.12. In order to reproduce with xtermjs
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io#snapshot/d6600439-765e-43a6-acb9-c4be29656b44)

**Comment by Tyriar** [comment]
@akosyakov tracking the remaining crash in https://github.com/xtermjs/xterm.js/issues/1932

**Comment by akosyakov** [comment]
Actually i'm not sure it is #1932. I can reproduce it with an example by changing cols between 10 and 80. Each time more and more lines appear but no errors in console like in #1932.

**Comment by Tyriar** [comment]
@akosyakov the errors in https://github.com/xtermjs/xterm.js/issues/1932 are just one of the errors that could happen if the buffer numbers are invalid, I think it just depends on what is run after the corruption occurs.
