### ISSUE TITLE
Use enums instead of string union types in API

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#2018]
Curious on @xtermjs/core's thoughts on this to improve intellisense for embedders: https://twitter.com/Tyriar/status/1118594371304087552

**Comment by mofux** [comment]
Not sure, if it means we have to do things like this to make it work, then I would be against it:

```typescript
import { ExpermintalCharAtlasOption } from 'xterm';
const config = {
  experimentalCharAtlas: ExperimentalCharAtlasOption.dynamic
}
```

As a side note - I'm also strongly against exporting enums via `const`:

```typescript
export const enum MyEnum {
  //...
}
```

Because it makes those enums inaccessible for vanilla Javascript code during runtime - const enums are inlined during typescript compile time and not exported in the final JS output, degrading Javascript to a second-class citizen.

IMO we should always prefer an API that works nicely for both, `typescript` and `javascript` devs, and it shouldn't rely on the comfort features vscode's Intellisense offers.

**Comment by Tyriar** [comment]
> ```ts
> import { ExpermintalCharAtlasOption } from 'xterm';
> const config = {
>   experimentalCharAtlas: ExperimentalCharAtlasOption.dynamic
> }
> ```

@mofux this is what I meant, the main benefit being we could describe dynamic when navigating the members in `ExperimentalCharAtlasOption`. Also this would only work if it was non-const (for exported members). Looking at it now, it's super verbose so i agree with you 🙂
