### ISSUE TITLE
Buffer.x and Buffer.y are not updated in realtime

### ISSUE THREAD

**Issue by p3nt4** [xtermjs/xterm.js#2022]
This might be related to https://github.com/xtermjs/xterm.js/issues/2021
Apologies if I am not using the api correctly.

## Details
- Chrome: Version 73.0.3683.103
- OS version: Windows 10
- xterm.js version: 3.12.0

### Steps to reproduce

1. Create code such as:
 ```
console.log(term._core.buffer.x);
term.write(longstring);
console.log(term._core.buffer.x);

```
4. Notice X has not been updated.

**Comment by Tyriar** [comment]
This is because parsing incoming data is fired asynchronously by design. Note that anything inside _core is private and you're not meant to be using. You will probably want https://github.com/xtermjs/xterm.js/issues/1994 when it gets in, in the meantime listen to `.on('cursormove')` to detect when changes to the buffer occur.
