### ISSUE TITLE
The .fit() method of the fit add-on does not work when loaded using the latest (^3.14.0) API

### ISSUE THREAD

**Issue by ardentia** [xtermjs/xterm.js#2265]
I am using xterm.js (as an npm package) in an Angular 8 project. I have a container with a specified height and I am calling the `.fit()` method of a new `FitAddon` instance I have created. I get the following error message: 
```ERROR TypeError: Cannot read property 'dimensions' of undefined at e.proposeDimensions (FitAddon.ts:20)```. 

When I inspect it through FitAddon.ts, I can see that it errors out on line 74: https://github.com/xtermjs/xterm.js/blob/master/addons/xterm-addon-fit/src/FitAddon.ts#L74. It turns out that `_renderService` prop does not exist on the Terminal prototype.

## Details
- Browser and browser version: Google Chrome Version 75.0.3770.100
- OS version: Windows 10
- xterm.js version: 3.14.2

### Steps to reproduce

1. Create a new Angular project
2. Add xterm.js and xterm-addon-fit as dependencies
3. Load the fit add-on
4. Call `.fit()` of the add-on

Here's a StackBlitz with the reproduced issue: https://stackblitz.com/edit/angular-wm1tmj (you need to open the dev console).

**Comment by Tyriar** [comment]
This is happening because of bad versioning in the new addons, we've learned that we'll need to add compatible versions to each release page in order to ensure compatibility. I'd say use the old `applyAddon` system until v4 lands when we should hopefully have sorted this out. Alternatively if you're brave and eager to try out the new addons you can use the latest `beta` build of both the `xterm` and `xterm-addon-fit` modules which are compatible.

I already made a note in the draft release notes but I also wrote up some notes about this as well so we don't forget in https://github.com/xtermjs/xterm.js/wiki/Releasing. Thanks for the feedback 😃
