### ISSUE TITLE
Manually draw pixel-perfect glyphs for Box Drawing and Block Elements characters

### ISSUE THREAD

**Issue by anatoly-spb** [xtermjs/xterm.js#2409]
## Details
- Browser and browser version: Chrome 76.0.3809.132 (64 bit), FireFox 69.0 (64 bit)
- OS version: Windows 7 Pro 64 bit
- xterm.js version: ^3.14.5

### Steps to reproduce

index.html:
```
<!doctype html>
<html>

<head>
	<link rel="stylesheet" href="node_modules/xterm/dist/xterm.css" />
	<script src="node_modules/xterm/dist/xterm.js"></script>
</head>

<body>
	<div id="terminal"></div>
	<script>
		var options = {
			rows: 30,
			cols: 80,
			fontFamily: '"Courier New", "DejaVu Sans Mono", "Everson Mono", FreeMono, "Andale Mono", monospace',
			fontSize: 12,
			convertEol: true
		};
		var term = new Terminal(options);
		term.open(document.getElementById('terminal'));

		term.write('           ╔═════════════════════════════════════════════════════════╕\n');
		term.write('           ║                                                         │\n');
		term.write('           ║              ╔═══════════════╦════════╤════════╗        │\n');
		term.write('           ║              ║               ║        │        ║        │\n');
		term.write('           ║              ║               ║        │        ║        │\n');
	</script>
</body>

</html>
```

![image](https://user-images.githubusercontent.com/13556403/64624362-3a4ab900-d3f3-11e9-83c0-43c95d129c86.png)

There are several related issues but it does not help:

https://github.com/xtermjs/xterm.js/issues/475
https://github.com/xtermjs/xterm.js/issues/992

**Comment by Tyriar** [comment]
I think this depends on the font being used, I can't repro using the canvas (default) renderer.

**Comment by anatoly-spb** [comment]
@Tyriar how can I share the needed info?

**Comment by Tyriar** [comment]
Can you try using [this font](https://sourcefoundry.org/hack/)? Both your fontFamily and Hack work for me on my Windows 10 box.

**Comment by anatoly-spb** [comment]
I have tried the following on my home Windows 10 64 bit machine in Yandex Browser (based on Chromium):
```
<!doctype html>
<html>

<head>
	<link rel='stylesheet' href='//cdn.jsdelivr.net/npm/hack-font@3.3.0/build/web/hack.css'>
	<link rel="stylesheet" href="node_modules/xterm/dist/xterm.css" />
	<script src="node_modules/xterm/dist/xterm.js"></script>
</head>

<body>
	<div id="terminal"></div>
	<script>
		var options = {
			rows: 30,
			cols: 80,
			fontFamily: 'Hack',
			fontSize: 12,
			convertEol: true
		};
		var term = new Terminal(options);
		term.open(document.getElementById('terminal'));

		term.write('           ╔═════════════════════════════════════════════════════════╕\n');
		term.write('           ║                                                         │\n');
		term.write('           ║              ╔═══════════════╦════════╤════════╗        │\n');
		term.write('           ║              ║               ║        │        ║        │\n');
		term.write('           ║              ║               ║        │        ║        │\n');
	</script>
</body>

</html>
```
Here is the result:
![image](https://user-images.githubusercontent.com/13556403/64645172-f10f5f00-d41c-11e9-8a06-36e2facdc758.png)

**Comment by egmontkob** [comment]
FYI: Some terminals, including gnome-terminal (vte) and konsole manually draw the U+2500..257F (or even up to 259F) characters, rather than taking them from the font, in order to provide beautifully connected look.

Coincidentally both of these emulators took pretty similar technical approach: define the look of (most of) these glyphs as a [5x5 bitmap](https://gitlab.gnome.org/GNOME/vte/blob/0.58.0/src/box_drawing.txt) with uneven "pixel" sizes that are computed runtime based on font size.

**Comment by egmontkob** [comment]
Now that #2572 has been marked as dup, this bug is definitely about [U+2500..257F "Box Drawing"](https://www.unicode.org/charts/PDF/U2500.pdf) and [U+2580..259F "Block Elements"](https://www.unicode.org/charts/PDF/U2580.pdf) too.

Also keep an eye on forthcoming (Unicode 13) [U+1FB00 "Symbols for Legacy Computing"](https://www.unicode.org/Public/13.0.0/charts/blocks/U1FB00.pdf), see e.g. [VTE 189](https://gitlab.gnome.org/GNOME/vte/issues/189).

**Comment by jerch** [comment]
@egmontkob Lol, I guess those newish glyphs are meant to align perfectly as well? Geez, who needs a font renderer, if one can do it the hard way...

**Comment by egmontkob** [comment]
I'd love to understand the reasons none of the fonts gets it right. But I don't have time and motivation to investigate.

**Comment by Tyriar** [comment]
One interesting thing this could do that fonts couldn't is fill the entire cell when a line height is specified.

**Comment by nojus297** [comment]
Additional funny behavior (vscode terminal):
![out3](https://user-images.githubusercontent.com/46261165/79368566-4766f200-7f58-11ea-99e7-1c891dd77e5f.gif)
For me, changing font sizes, using the previously mentioned `hack` font does not help, the spacing remains. However, judging from the gif above, the block characters seems to be placed incorerctly. There is one pixel gap at the bottom and the difference between 7/8 and 8/8 (full) blocks seems smaller than between the other ones.

**Comment by guregu** [comment]
On macOS (Retina screen, devicePixelRatio=2.200000047683716) + Chrome, using the Hack font gives me small vertical gaps like this:
<img width="135" alt="Screen Shot 2020-04-28 at 20 44 51" src="https://user-images.githubusercontent.com/131059/80484661-0bd61a00-8993-11ea-8a19-19ba2c4e2dcb.png">
But after poking around I noticed that turning `BaseRenderLayer._clipRow` into a no-op renders them correctly:
<img width="137" alt="Screen Shot 2020-04-28 at 20 44 40" src="https://user-images.githubusercontent.com/131059/80484766-3a53f500-8993-11ea-8331-166074cab1aa.png">
which leads me to believe that this might be a clipping issue.

**Comment by Tyriar** [comment]
@guregu the canvas renderer by design must clip the rows or it will end up having artifacts showing up, but anyway the plan is to remove the canvas renderer in favor of DOM and webgl (basically superior in every way to canvas).

This is still marked as help wanted and maybe it can/should only be done in the webgl renderer in which case it would be a matter of handling those particular characters specially when drawing the char to the texture atlas:

https://github.com/xtermjs/xterm.js/blob/45077d710627fb2aec61ac2dfc41879d8c32371e/addons/xterm-addon-webgl/src/atlas/WebglCharAtlas.ts#L304-L306

**Comment by guregu** [comment]
FWIW I've managed to fix it without messing with the clipping.
The problem wasn't the clipping, but using `middle` as the `textBaseline` caused it to be slightly misaligned.
Changing the `textBaseline` to `bottom` totally fixed the issue for me.
Diff: https://github.com/xtermjs/xterm.js/compare/master...guregu:master
I can send a PR if it looks good, but I'm not sure if this will screw something else up.

Is there a particular reason it was set to `middle` before?

Here's a screenshot of the code running from the start of this without the fix:
<img width="507" alt="Screen Shot 2020-04-28 at 22 29 03" src="https://user-images.githubusercontent.com/131059/80492977-b6ecd080-899f-11ea-80ac-4c4f60565695.png">
Here it is with the fix applied:
<img width="501" alt="Screen Shot 2020-04-28 at 22 24 19" src="https://user-images.githubusercontent.com/131059/80493000-c1a76580-899f-11ea-9816-844cb070b1c0.png">

**Comment by Tyriar** [comment]
@guregu previously the webgl renderer used top, but it ended up making the text top aligned:

![image](https://user-images.githubusercontent.com/2193314/80495053-43ee4600-891c-11ea-8504-6566542e660f.png)

I fear this will happen if we use `bottom`

**Comment by Tyriar** [comment]
It's also not perfect even ignoring the bottom alignment problem:

![image](https://user-images.githubusercontent.com/2193314/80495297-99c2ee00-891c-11ea-9196-9c1ee03a349d.png)

I think manually drawing perfect glyphs is the way to go.

**Comment by jerch** [comment]
Btw @nojus297 output pretty much looks like an 0.5 px offset issue. I stumbled over antialiasing issues with a 0.5 offset myself the other day, when I messed around with self-drawn curly underlines. Not sure if this applies here at all (still not used to the renderer code lol).

**Comment by Tyriar** [comment]
Would could check your zoom level as well to make sure it's 1. Should we maybe be bumping it down 0.5px when the font size is odd? 🤔

**Comment by guregu** [comment]
I took screenshots of both my changes and the unchanged version and ran a diff on them. Normal text actually renders exactly the same. The only difference is the drawing characters.
![download](https://user-images.githubusercontent.com/131059/80502523-b9edbe00-89ab-11ea-87a9-4c298ab62a2a.png)
(the magenta is the differing part)

Basically the crux of this issue is that, for some reason, text that takes up the entire height of a cell gets pushed up a few pixels and clipped out when using `middle` as the `textBaseline`. 
It's easy to verify this if you highlight it. 
<img width="105" alt="XTERM_BROKE" src="https://user-images.githubusercontent.com/131059/80504414-0b974800-89ae-11ea-858c-f8c126d567bf.png">
^ unfixed version, you can see that there's a few empty pixels at the bottom of the ║

Regarding the notches on the horizontal line, Terminal.app appears to have the same problem. Maybe it's a font issue? No idea.
Screenshot from Terminal.app:
<img width="473" alt="Screen Shot 2020-04-29 at 0 02 04" src="https://user-images.githubusercontent.com/131059/80503899-74ca8b80-89ad-11ea-97d6-cca98cc144c9.png">

However, even with the changes I still see some weirdness, like using the cursor causes tiny black notches to show up. This doesn't happen on the veritcal ones. Maybe related to the other notches?
This is from xterm.js, and happens on both the changed and unchanged versions:
![rendering-oddness](https://user-images.githubusercontent.com/131059/80504173-c96e0680-89ad-11ea-839c-ad445399d28e.gif)

Anyway, I agree rendering these characters specially is the way to go. Just trying to find the reason this is happening in the first place.

**Comment by guregu** [comment]
I had some friends test out my fix on Windows and it actually makes things worse 😅 
Looks like special casing it is the only surefire way. Sorry about that. 
The cursor thing is probably a separate issue. Clearing the whole canvas during clearCursor fixes it. Seems like the horizontal box-drawing character is drawing a bit wider than the cell width?

**Comment by Tyriar** [comment]
@guregu thanks for looking into it.

> Seems like the horizontal box-drawing character is drawing a bit wider than the cell width?

Maybe, we allow that. Something that may work is to clip the character glyph to the size of a cell only for these box drawing characters?

**Comment by guregu** [comment]
I've done some experimenting with manually certain characters.
Demo page: http://roguelike.solutions/xterm/xtermtest.html

Code is rough, but available here: https://github.com/xtermjs/xterm.js/compare/master...guregu:box-drawing

Currently, it's two parts, one is `boxDrawingLineSegments` which borrows an algorithm from iTerm2. It defines 7 kind of arbitrary vertical and horizontal anchor points per character cell and strokes lines or curves corresponding to them. This works for almost all of the box-drawing lines, but doesn't work for the dotted line characters which require more anchor points. Having precise control over drawing the lines also means we don't need to clip horizontally to avoid spillover. I'm trying to think of a better way to represent these that will also work with the dotted lines. 
Perhaps instead of splitting cells into 7 somewhat-arbitrary points, instead we can define the locations like "left", "center", "center minus n devicePixelRatio pixels", etc. 
Also, iTerm2 is GPL2 and I tried to write it to be as original as possible and avoid license issues, but I'm not sure where the figurative line is drawn here. This is another reason to use a fancier original algorithm. Consider the current implementation a proof of concept. 

Next is `boxDrawingBoxes` (needs a better name 😅) which splits a character cell into eighths and fills in rectangles corresponding to them.  This is sufficient to draw the solid block characters, including new ones from the Symbols for Legacy Computing block. This should be enough to support the quadrant characters too, but in order to support sextants it will need to split characters into sixths. Allowing a divisor to be defined would be enough to support most block-like characters.

I don't yet support the polygon characters from the Symbols for Legacy Computing block, but using similar techniques should work for them. I'm not sure how to go about drawing the shade characters like ░ ▒ ▓, but maybe they could be special-cased. There's also the question of how far we want to go with this.

To clean the code up, maybe we could define an interface for drawing segments, and its implementors could be lines, curves, n-th boxes, etc. This is all very experimental, but if it seems like a good idea I'd be happy to contribute (and add support for the WebGL renderer).

**Comment by Tyriar** [comment]
> This is all very experimental, but if it seems like a good idea I'd be happy to contribute (and add support for the WebGL renderer).

@guregu nice work, a contribution would be awesome, you just need to make sure it's not too derivative of the iTerm2 algorithm as GPL2 is sticky. I'd suggest only doing this for the webgl renderer (not canvas as it's going to be scrapped). Definitely based the lines on devicePixelRatios so the width is great on all monitors.

> but using similar techniques should work for them. I'm not sure how to go about drawing the shade characters like ░ ▒ ▓

These should be relatively easy to do but this could easily be deferred as well. The main problem in this area are the solid ones.

**Comment by Tyriar** [comment]
@meganrogge and I just finished this, here's the result:

Canvas (1.1 line height, 1 letter spacing):

![image](https://user-images.githubusercontent.com/2193314/130069068-62b21542-265e-46bf-a3ff-58902b23cd66.png)

Webgl (same):

![image](https://user-images.githubusercontent.com/2193314/130070120-24e5f0cb-e2fd-4369-9212-af6508c21a2b.png)

**Comment by jerch** [comment]
@Tyriar Wow, nice work. :+1:  So many pretty boxes - must be xmas already, wonder whats inside :thinking:

**Comment by Tyriar** [comment]
> Any idea for the DOM renderer yet? Just give any box glyph a tiny bigger font-size?

For the DOM renderer I'm not sure we want to add the complexity there of rendering custom glyphs. Especially since I want to make the canvas renderer its own addon which would mean we don't even need the custom glyph code in the core xterm.js bundle.

> how about those other underline styles/colors?

I think underline styles and colors run into issues packing those bits in, there's also the issue that they probably can't just be added to the glyphs like this since they're repeating patterns that would get cut off, ie.

![image](https://user-images.githubusercontent.com/2193314/130086917-9efa608f-78fd-4507-966c-59ba1c23ef41.png)

---

Also special callout to @guregu whose work this builds upon ❤️

**Comment by jerch** [comment]
> ... they probably can't just be added to the glyphs like this since they're repeating patterns that would get cut off ...

This was my observation as well when playing around with it here: https://github.com/xtermjs/xterm.js/issues/1145#issuecomment-596726140

To me it seems underline might need its own render layer with its own progression only loosely coupled to glyph runwidths (like the wave period depends on the cell's global line position not trying to tie it's shape to glyph start). I learned that lesson when debugging browsers standard behavior, which tries to tie the dashed/dotted shaped perfectly on glyph start, but they kinda fail at various font size miserably (see images in other comment [above](https://github.com/xtermjs/xterm.js/issues/1145#issuecomment-596265394)).

**Comment by Tyriar** [comment]
That's what the link render layer is which is actually also used in webgl for convenience, it just covers hover link underlines right now.

It could be done in it's own webgl render pass as well, using an underline style texture atlas and coordinates.
