### ISSUE TITLE
Add a charset conversion helper function/callback?

### ISSUE THREAD

**Issue by niruix** [xtermjs/xterm.js#2461]
Hello, cool people of this project,

I'm working on a web ssh software which must support multiple terminal charsets (Not just UTF-8, but also GBK, BIG5 etc).

The method that I'm currently using is to convert everything to UTF-8 before `write` them to `xtermjs`.

However, I found that in order to correctly convert between charsets, from GBK to UTF-8 (For web browsers) for example, I must pre-parse all the terminal escape sequences so I can selectively convert embedded regular characters while leave escape sequence itself untouched, which is kind difficult.

Since `xtermjs` already doing the parsing itself, the solution in my imagination is to add a conversion callback function to `xtermjs` which will be called to convert _non-escape sequence characters_ (Or regular characters) to wanted charset.

The callback takes only _non-escape sequence characters_ (provided by `xtermjs` escape sequence parser, maybe) as parameter and returns a converted Array of the characters as output. The output is what will be escaped as regular characters, then printed on the screen or send to `onData` callback.

The usage can be like:

    term.addInputEncodingConversionHandler(data => {
        // data could be an Uint8Array, which will only contain non-escape sequence characters
        return convertToUTF8From("gbk", data); // Returns UTF-8 characters converted from GBK
    });

    term.addOutputEncodingConversionHandler(data => {
        return convertToGBKFrom("utf-8", data);
    });

If the above is too hard to implement, then maybe at least expose all the control codes used by the terminal (For example, everything inside of `xterm.js/src/common/data/EscapeSequences.ts`)  please? It will provide a clear target for me to work on my own pre-parser.

Thank you!

(Sorry for my poor English)

**Comment by jerch** [comment]
@niruix Not sure if there is a misconception on your side - with the advent of unicode and unicode support in emulators (xterm.js is unicode based as well) the general idea to deal with escape sequences is to encode them as well (e.g. 8-bit control chars are 2 byte long in UTF-8), thus the encoding is more like a full stream/transport encoding. xterm.js does this - it maintains two full stream IO decoder before any parsing happens (one for JS string as UTF16 and one for UTF-8 bytes). I strongly advice you to go with that option and either use `luit` for stream re-encoding or write your own custom BIG5 to Unicode converter to be hooked into xterm.js later on.

The said above is not true for older legacy terminals with dedicated foreign encoding support, those would treat string parts of the stream differently and keep control sequences in 7 or 8 bit (depending on the encoding). xterm.js does not support that operation mode, we are strictly bound to Unicode input and have no plans to extend this into the legacy direction. If you have access to very old machines with those mixed up terminal input, you are kinda out of luck. Again try out `luit`, it works at least for most ISO8869 encoding reliably.

If this still doesnt help - then you are kinda out of luck and have to pre-parse the stream data to slice and re-encode the string parts into proper Unicode (UTF-8). You cannot even c&p our parser for that, since it already assumes/operates on UTF-32 (thus input data must comply Unicode). You might get away with small chances to our parser though, depending on how badly screwed up the mixed encoding is.

Your suggested API additions will not work, as xterm.js decodes data much earlier, not on parsing level. I suggest to to take the parser and alter it to your needs (prolly needs a custom `parse` method and support for byte input).
