### ISSUE TITLE
Close on decision regarding 0-based and 1-based coordinates in API

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#2484]
https://github.com/xtermjs/xterm.js/pull/2470 added the 1-based interface `IViewportCellPosition` (uses col/row, aligns with [how escape sequences work](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html)), https://github.com/xtermjs/xterm.js/issues/2480 will add `IBufferCellPosition` (x/y) which may be 0-based? Is that confusing? What should we do?

@mofux tells me monaco uses 1-based and language servers use 0-based. Maybe we should just use 0-based everywhere (should we avoid col/row in the API)?

**Comment by jerch** [comment]
@Tyriar Imho 0-based is more natural to programmers as almost everything is 0-based. Also internally we have >90% 0-based and convert most 1-based stuff as soon as possible. To me most 1-based use cases in progamming feel like a mistake. (Does FORTRAN still have its 1-based array types?)

My vote goes to 0-based. :smile_cat:

**Comment by Tyriar** [comment]
@jerch in that case should we use `x`/`y` for `IViewportCellPosition` as well? "0th col" and "0th row" feels wrong.

**Comment by jerch** [comment]
Right - for 0-based x/y seems better, as it clearly refers to coords/index viewpoint (where most ppl would expect 0 as origin). col/row is more on the counting side of things, "0th col" feels like something not existent.

**Comment by mofux** [comment]
@jerch explanation sounds very reasonable to me. A 0-based `IViewportCellPosition` with `x`/`y` would be my preferred solution.

**Comment by Tyriar** [comment]
👍 tracking this to change it before we release.

**Comment by egmontkob** [comment]
Not my project, I don't even know what APIs you have, so feel free to ignore this comment :)

I recently did some cleanups in VTE around this area; in particular, about ranges being end-inclusive or end-exclusive (or, well... wait for it).

Some APIs I can imagine work with a single item of whatever (e.g. what's the letter in a certain character cell), while I can imagine APIs that work with ranges (e.g. what's the text in that range; what's the range selected with mouse, etc.).

In my experience, the only sensible way to think about _ranges_ is that start and end are not items, but _boundaries_ between items. See e.g. string slicing in Python for a beautiful example. And with boundaries, obviously the only reasonable thing is to start counting at 0 (for the boundary before the first item). Plus, luckily, the dilemma of end-inclusive vs. end-exclusive is no more.

And once you go with this for ranges, the intuitive follow-up is to refer to a particular _item_ (if that's what you need to do) beginning with 0, too. It's just way more intuitive to say "the item after this boundary" rather than "the item before this boundary". I haven't seen the latter approach anywhere, this would be an anti-pattern for software developers.

(On a side note, 0-based is what you need for the rectangle and I-beam cursor shapes to both make sense, with the same numbering scheme independently of the shape.)

The computer world figured this out long ago, the clear answer is always to go for 0-based. Who cares that 60 years ago Fortran didn't have today's expericene? (Well, obviously I understand that the fact that terminal escape sequences got it wrong too, which sucks, is the reason why you're considering 1-based as an option.)

**Comment by egmontkob** [comment]
> "0th col" and "0th row" feels wrong.

Rephrase to "column 0", "row 0", they are okay.

**Comment by jerch** [comment]
@egmontkob About end-inclusive/exclusive I had a similar trick to memorize it - I imagined the index values as being "half left shifted" to the real item - in a row of buckets the gaps between. It logically leads to left-inclusive / right-exclusive.
But I never counted items starting at 0th, in my world index 0 to index 1 form a slot that holds the 1st item (or to read it in indices - you have to go from index 0 to index 1 to count one or the 1st item and so on; and the stopping index automagically denotes the number of items == length).

I think some ppl have troubles to tell which cell a block cursor in a terminal will alter next in either direction for the same reason. Much easier to comprehend with a beam cursor...

**Comment by egmontkob** [comment]
> It logically leads to left-inclusive / right-exclusive.

Yup, which is most of the much better than right-inclusive.

> But I never counted items starting at 0th, in my world index 0 to index 1 form a slot that holds the 1st item

Interesting approach. Don't you have off-by-one troubles when working with array indices in pretty much every language, since you access that item as `[0]`? :)

> I think some ppl have troubles to tell which cell a block cursor in a terminal will alter next in either direction for the same reason. Much easier to comprehend with a beam cursor...

I fully agree, I've been using I-beam cursor for years for reasons along these lines (especially when highlighting a range in some app I find the block cursor quite confusing).

**Comment by jerch** [comment]
> Interesting approach. Don't you have off-by-one troubles when working with array indices in pretty much every language, since you access that item as [0]? :)

Lol 100% - the problems start when ppl address the item instead of the index. I guess cols are 1-based for that reason, in punch card times there was no meaningful 0th column as a physical thingy. For [0] itself - that no problem as its the index :smile_cat:

**Comment by egmontkob** [comment]
Oh, I see. When speaking English (rather than a programming language) I'm also always confused whether to say 0th or 1st, or for the next item 1st or 2nd... But for programming languages (APIs etc.) it's almost always the 0-based that is better.

**Comment by jerch** [comment]
Yes, imho all the confusion comes from natural language usage (or trying to apply simple counting rules - a mistake found in those very early programming languages as well). The 1-based cat is already out of the bag - hard to put it back...

**Comment by Tyriar** [comment]
> In my experience, the only sensible way to think about ranges is that start and end are not items, but boundaries between items.

This was actually the reason for the decision in the how mouse zones worked if I remember right. Getting a selection position back of 0 to 0 is plain weird, plus a zero-length selection is perfectly (consider holding the mouse down and moving it away and then back to its original position).

**Comment by Tyriar** [comment]
Ok, let's go with 0-based and have the end range `x` be exclusive so it's consistent everywhere as I think we have to keep selection like that.

**Comment by Tyriar** [comment]
PR out: https://github.com/xtermjs/xterm.js/pull/2512
