### ISSUE TITLE
Character size computation is affected by CSS transforms

### ISSUE THREAD

**Issue by cebamps** [xtermjs/xterm.js#2488]
When a Terminal is opened in an element subject to CSS transformations such as `scale` or `rotate`, the computation of the character size is affected by that transformation, which is wrong because the rendering should be transform-agnostic.

As a result, this makes the integration of Xterm.js into reveal.js slides render incorrectly when the slides are scaled down to fit the browser viewport.

Changing the measurement method in `CharSizeService` to use `getComputedStyle` instead of `getBoundingClientRect` makes the computation independent of CSS transforms.

## Details
- Browser and browser version: Firefox 69.0 and Chromium 77.0
- OS version: Arch Linux
- xterm.js version: current master (6311076)

### Steps to reproduce

1. Add `style="transform: rotate(90deg);"` to the `<body>` tag in `demo/index.html`
2. Notice that character boxes in the demo have the wrong dimensions

### Workaround

With the `rotate(90deg)` CSS transform Xterm.js renders character cells with the width and height swapped around:
![getBoundingClientRect](https://user-images.githubusercontent.com/12797742/67163766-28a1ed00-f373-11e9-953d-f3894e5550e3.png)

The cause is in the measurement methods in `CharSizeService`: it uses `getBoundingClientRect`, which returns the size of the bounding box *after* CSS transforms.
https://github.com/xtermjs/xterm.js/blob/631107698ec1f28577101cc570540f097a83af68/src/browser/services/CharSizeService.ts#L71-L86

My understanding is that the rendering of the terminal should not be affected by said transforms. And indeed, replacing the `geometry` definition in the code above with (POC)
```ts
    const computedStyle = getComputedStyle(this._measureElement);
    const geometry = {
      height: Number(computedStyle.getPropertyValue('height').replace('px', '')),
      width: Number(computedStyle.getPropertyValue('width').replace('px', '')),
    }
```
yields a correct rendering:
![getComputedStyle](https://user-images.githubusercontent.com/12797742/67163767-28a1ed00-f373-11e9-9f16-289156334758.png)

Note that my proof-of-concept fix above may be insufficient in cases where the element or its parent are `display: none`.

**Comment by Tyriar** [comment]
@cebamps the workaround seems reasonable.

> Note that my proof-of-concept fix above may be insufficient in cases where the element or its parent are display: none.

I don't think this should matter.

**Comment by leomoty** [comment]
I am not really able to reproduce. The selection with cursor is broken when you rotate the terminal.

**Comment by Tyriar** [comment]
Still reproduces:

![image](https://user-images.githubusercontent.com/2193314/207902630-71f7d18a-8edd-4921-abf7-f2373fbef2b2.png)

**Comment by jerch** [comment]
Oh well, wasnt aware if this - also needs to be changed in #4605.

**Comment by catpea** [comment]
Another way to recreate a scale() flavor of the incorrect calculations due to CSS transforms is to go to the homepage, open web developer tools in your browser and in CSS pane click add new rule and:

```css
/* to see the problem add CSS rule to https://xtermjs.org/ */
main {
  transform: scale(0.5);
}
```

Try selecting text in the scaled terminal, and beginning of the selection will not match the cursor position. I am using 5.5.0, getting the same problem, not sure what the  website is using. I apologize if this is already fixed in beta, I only have a moment to type this up and without fit plugin I can't install beta.

My solution is to expose a .transform function that will transform x and y that the mouse service is using. In my application xterm is inside a svelte app, nested inside an svg foreignElement, inside an svg, inside a custom vanilla js framework. And I am using the concept of a zooming user interface with Multiple Dialog/Document Interface that also supports zoom. .transform function may seem clunky but it is flexible.

And I wanted to report that CodeMirror 6 https://codemirror.net/ code editor does not have the same problem. Maybe they have a generic solution.

Also the solution may need to be tested against 3D embedding as shown on https://retejs.org

Thank you for such a wonderful gem of a program.

Ps.

```Here is a response from GPT 4 turbo when I asked it about the problem, forgive me I am exhausted, I have no time to read it, and assume it is a hallucination```

Step by Step Guide to Get Correct Mouse Coordinates

Step 1: Listen for Mouse Events

First, set up an event listener for mouse events like mousemove, mousedown, or mouseup on the canvas.

```JavaScript

const canvas = document.getElementById('yourCanvas');
canvas.addEventListener('mousemove', function(event) {
    const {x, y} = getMousePos(canvas, event);
    console.log('Mouse position:', x, y);
});

```

Step 2: Calculate Mouse Position

Create a function getMousePos that takes the canvas element and the event as arguments. This function will calculate the correct coordinates.

```JavaScript
function getMousePos(canvas, evt) {
    let rect = canvas.getBoundingClientRect();
    let sx = rect.width / canvas.width;
    let sy = rect.height / canvas.height;

    let scaleMatrix = getTransformationMatrix(canvas);
    let transformedPoint = applyMatrixToPoint(scaleMatrix, {
        x: (evt.clientX - rect.left) / sx,
        y: (evt.clientY - rect.top) / sy
    });

    return transformedPoint;
}
```

Step 3: Accumulate Transformations

Create a function getTransformationMatrix that walks up the DOM tree from the canvas, accumulating all transformation matrices.

```JavaScript
function getTransformationMatrix(element) {
    let identityMatrix = DOMMatrix.identity();
    var transformMatrix = identityMatrix;

    while (element) {
        const style = window.getComputedStyle(element);
        const transform = style.transform || 'none';
        const matrix = transform === 'none' ? identityMatrix : new DOMMatrix(transform);
        transformMatrix = matrix.multiply(transformMatrix);
        element = element.parentElement;
    }

    return transformMatrix;
}
```

Step 4: Apply Transformation Matrix to Point

Define a function that applies the transformation matrix to a point.

```JavaScript
function applyMatrixToPoint(matrix, point) {
    const domPoint = new DOMPoint(point.x, point.y);
    const transformedPoint = dompoint.matrixTransform(divMatrix.inverse());
    return {
        x: transformedPoint.x,
        y: transformedPoint.y
    };
}
```

Explanation:

- Step 1 and Step 2 handle the setup and initial scale adjustment.
- Step 3 is crucial because it accumulatively multiplies transformation matrices from the target canvas up to the root, ensuring that all transformations are considered.
-  Step 4 uses the cumulative matrix to transform the mouse point, effectively mapping it accurately according to the total transformation applied.

This method considers all transformations applied to the canvas and its parent elements. Ensure to test this thoroughly, especially in complex layouts. The calculation might need adjustments based on specific CSS configurations or additional transformations such as rotations which could need more complex computations to invert correctly.
