### ISSUE TITLE
Cursor foreground sits a bit lower than other text in the webgl renderer 

### ISSUE THREAD

**Issue by npezza93** [xtermjs/xterm.js#2613]
Using the webgl renderer it seems like selection highlight sits a bit lower than the canvas renderer. 
Webgl:
<img width="203" alt="Screen Shot 2019-12-06 at 10 40 19 AM" src="https://user-images.githubusercontent.com/5059927/70335233-eba39400-1814-11ea-9965-10cd3ac903ff.png">
canvas:
<img width="177" alt="Screen Shot 2019-12-06 at 10 41 42 AM" src="https://user-images.githubusercontent.com/5059927/70335293-0970f900-1815-11ea-9690-021c8732e273.png">

Here's an example where it looks like the characters drop when the cursor highlights them. Feels like the cursor needs to be moved up a few pixels.
![selection](https://user-images.githubusercontent.com/5059927/70335430-45a45980-1815-11ea-8801-a33cfbd04eae.gif)

This could perhaps be an issue with the font. Currently im using Fira Code and when using `courier-new, courier, monospace` the first issue doesn't happen but the second example does still happen.

## Details
- Browser and browser version: electron-7.1.3
- OS version: macOS catalina
- xterm.js version: 4.3
- xterm-addon-webgl version: 0.4.0

**Comment by Tyriar** [comment]
Oh the cursor not the selection. This is because of my new favorite Chromium bug https://bugs.chromium.org/p/chromium/issues/detail?id=1026254, https://github.com/microsoft/vscode/issues/84432

The reason it's different inside just the webgl renderer if because the exact same canvas is being used to render the cursor for both webgl and canvas, it's just another transparent canvas sitting on top of the webgl canvas. Same for links: 

https://github.com/xtermjs/xterm.js/blob/bd0d267d972a1aab4777cddecf9bf8196d7aa44f/addons/xterm-addon-webgl/src/WebglRenderer.ts#L54-L57

I'll leave this open as maybe I can look into not using `textBaseline` `middle`.

**Comment by Tyriar** [comment]
Created https://github.com/xtermjs/xterm.js/issues/2614 to remove cursor canvas
