### ISSUE TITLE
getSelection() does not return a single character selection

### ISSUE THREAD

**Issue by theflyingape** [xtermjs/xterm.js#2617]
Relates to: #2244 
This works fine when a double-click highlights a word selection > 1 character.  But if the selection only highlights a single character, getSelection() returns an empty string.  Is this by design?

## Details
- Browser and browser version: Chrome 78
- OS version: Linux
- xterm.js version: 4.3.0

### Steps to reproduce

1. ITerminalOptions.wordSeparator = \` .:;?!"'<>(/)[=]\`
2. term.write('Sex (M/F)? ')
3. double-click the 'M'
4. getSelection() returns ''

Online example: https://play.ddgame.us

**Comment by Tyriar** [comment]
I can't repro?

<img width="723" alt="Screen Shot 2019-12-07 at 9 55 25 AM" src="https://user-images.githubusercontent.com/2193314/70378646-b7dd7280-18d7-11ea-9f8d-583225830285.png">

**Comment by theflyingape** [comment]
Did you double-click the **M**?  It works if you click&hold and select a single character.
Perhaps this missing info is crucial here... my getSelection() occurs within the onSelectionChange() event, i.e.,
```
	term.onSelectionChange(() => {
		if (carrier) {
			let word = term.getSelection()
			if (word.length > 0 && word.length < 64) {
				socket.send(word + '\x0D')
				term.clearSelection()
			}
		}
	})
```

**Comment by Tyriar** [comment]
@theflyingape I do see double clicking not sending sometimes, maybe the event isn't firing or something?

**Comment by daniel-j-davis** [comment]
I took a shot at looking into this and seems like it's related to onMouseUp in the SelectionService... https://github.com/xtermjs/xterm.js/blob/afc39106c3707532136c0818e9d3aa1dbcf176ac/src/browser/services/SelectionService.ts#L665
https://github.com/xtermjs/xterm.js/blob/afc39106c3707532136c0818e9d3aa1dbcf176ac/src/browser/services/SelectionService.ts#L670
https://github.com/xtermjs/xterm.js/blob/afc39106c3707532136c0818e9d3aa1dbcf176ac/src/browser/services/SelectionService.ts#L671

The problem is that if the length of selectionText is <= 1, but ```event.altKey``` doesn't return true, the selection gets thrown away and `this._onSelectionChange.fire()` doesn't get called. Is there a reason that we can't just always call `this._onSelectionChange.fire()`, even if `event.altKey` is true?

Thoughts? @Tyriar @theflyingape

**Comment by Tyriar** [comment]
@daniel-j-davis good find! Moving this `event.altKey` up one line would probably fix it, do you want to do a PR?

https://github.com/xtermjs/xterm.js/blob/afc39106c3707532136c0818e9d3aa1dbcf176ac/src/browser/services/SelectionService.ts#L670-L671

**Comment by daniel-j-davis** [comment]
@Tyriar Yeah, that works too and I've verified that alt+click still works as expected.

**Comment by theflyingape** [comment]
4.7.0 works great, thanks!
