### ISSUE TITLE
Feature to support auto-growing the viewport

### ISSUE THREAD

**Issue by sdegutis** [xtermjs/xterm.js#2624]
Ultimately I'd like to be able to have the viewport start off with 1 row, even though the underlying PTY thinks it has 24 rows, and reports this to programs. And when I pass data to xterm.js that tries moving within the 80x24 viewport that's valid, the actual viewport grows to include enough rows for the operation to happen.

What I do right now is run the following code every time I call `term.write(data)` (within a setTimeout of 0 seconds needed for some reason):

```js
if (term.buffer.length > term.rows && term.buffer.length < 20) {
  term.resize(term.cols, term.buffer.length);
}
```

This does work when `\n` is encountered, but not `ESC [ 4 ; 4 H` for example. It will move to 4x1 on the current 80x1 viewport.

I could just parse the escape codes myself, but xterm.js already does this. There is a callback for this event, `term.onCursorMove`, but it doesn't provide enough information for me to know how many more rows need to be added:

```js
term.onCursorMove(() => {
  // term.buffer.baseY      = 0
  // term.buffer.cursorX    = 3
  // term.buffer.cursorY    = 0
  // term.buffer.length     = 1
  // term.buffer.viewportY  = 0
});
term.write('\x1b[4;4H');
```

Maybe this callback could be given the specific movement information? That might be enough to help me implement the rest of this feature externally.

**Comment by sdegutis** [comment]
I think this is the function where the `onCursurMove` callback is called:

https://github.com/xtermjs/xterm.js/blob/397d053e0682902a85b7637ff1605b22ed9ef266/src/InputHandler.ts#L336-L376

It looks like all the heavy lifting is done by one of the polymorphic parsers. I think [EscapeSequenceParser](https://github.com/xtermjs/xterm.js/blob/397d053e0682902a85b7637ff1605b22ed9ef266/src/common/parser/EscapeSequenceParser.ts) is probably the one most likely to interpret all cursor movement codes.

Maybe these can store information when more specific types of cursor movement happens, and this function can retrieve that and call a callback with it?

**Comment by jerch** [comment]
@sdegutis To be more precise on the parser stuff - strictly seen is `EscapeSequenceParser` more like a terminal sequence tokenizer, that hands the dirty work to registered sequences handlers (the defaults are implemented in `InputHandler` methods and registered in the ctor).

You are right about `InputHandler.parse` and the cursor move event, but note that this is abit hackish atm and might not reflect what the name suggests:
- gets only fired between single `Terminal.write` chunks
- does not fire when the cursor happens to end up at the same cell again

I stumbled myself over this several times, but since it was no real issue so far on integration side I did not address it yet. Ideally the event would be fired whenever the cursor was moved, no matter where it ends up, but thats not easy to accomplish without big perf sacrifices. So there has to be some "debounce" - which happens to be the chunk border atm. Still this is a weird and "artificial" choice (write chunks might get split by transport layers at random locations).

About cursor movements in general - there is currently no single entry that can spot all cursor move sequences, its scattered over several methods. `EscapeSequenceParser` should not get that functionality, it does not deal with any context information beside the terminal sequence type (and cursor moves will happen by different types, thus its orthogonal to the sequence type). A better way to deal with this might be a cursor class that deals with the low level cursor updates (could be part of #2290).

**Comment by sdegutis** [comment]
Thanks @jerch. That sounds like a far-reaching change with a lot of room for mistakes, and I'm not sure I'm qualified to jump right into the codebase to tackle that.

**Comment by jerch** [comment]
@sdegutis I hear you, such a cursor class needs careful crafting and testing, as it must incorporate many weird terminal states to handle border restrictions correctly (like top/bottom/left/right borders with different conditions under DECOM and DECLRMM with correct rightmost cell handling).

Originally I felt the need for such a class when I fixed many state issues in #2288 and #2355, it was quite hard to adopt the right handling due to the scattered cursor code - and you know for sure that there is a fundamental abstraction flaw if you fix one issue but introduce two new ones at different places. Sadly our cursor/cell handling has such a flaw with the cursor at the rightmost cell and the way we deal with wrapped lines (#1882 and #2359). Well its not as bad as it sounds here - we managed to get it working for >95% of all use cases, still the flaw keeps us from getting those issues fixed.

So my hope with a cursor class is to encapsulate some of the weird low level issues into one place to get a better separation of concerns (easier to fix and maintain). Still the class will be a state condition monster...

For your issue at hand: the slightly flawed event is only way we expose cursor changes atm.

**Comment by sdegutis** [comment]
In the meantime I came up with a stop-gap solution. It's the same as the first solution I mentioned here, checking term.buffer.length and term.rows, but it also checks if there are any escape codes that don't match color codes, in which case it expands to the full rows.

**Comment by Tyriar** [comment]
We wouldn't want to bring this sort of thing into core, fixing the event is good though. Should we close this in favor of https://github.com/xtermjs/xterm.js/issues/2290?

**Comment by sdegutis** [comment]
Sure I think that's reasonable.
