### ISSUE TITLE
Powerline fonts not rendered properly using WebGL

### ISSUE THREAD

**Issue by chesteripz** [xtermjs/xterm.js#2645]
The powerline fonts are not rendered properly with WebGL enabled.

## Details
- Browser and browser version: MS Visual Studio Code, v1.41.1
- OS version: Windows 10 1909
- xterm.js version: 4.3.0-beta.28.vscode.1

### Steps to reproduce

1. Install `Menlo for Powerline`
2. Enable WebGL rendered in VS Code as follow:
```json
{
    "terminal.integrated.rendererType": "experimentalWebgl"
}
```
3. Install `zsh` 
4. Enable `powerlevel9k` theme
5a. The characters are not aligned properly.
![image](https://user-images.githubusercontent.com/23096845/71319672-612d8680-24dc-11ea-92a8-8ed8b3e88972.png)
6b. And selection does not inverse the color.
![image](https://user-images.githubusercontent.com/23096845/71319678-67236780-24dc-11ea-994b-390a88d6b17b.png)

**Comment by jerch** [comment]
> 5a. The characters are not aligned properly.

@Tyriar  Already figured that myself - seems the chars are not centered in the "cell" (printed slightly off to the top)

> 6b. And selection does not inverse the color.

@chesteripz This is kinda expected behavior here - we use a different way to colorize selections than swapping foreground and background. Selecting the prompt reveals, that powerline "hacks" the colored arrows with background color + a colored character (which is in the foreground).

**Comment by Tyriar** [comment]
@jerch this one is just that Chromium bug with `textBaseline` https://github.com/xtermjs/xterm.js/issues/2613
