### ISSUE TITLE
Renderer is blurry when window zoom level is changed

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#2662]
https://github.com/xtermjs/xterm.js/issues/985#issuecomment-570037111

Right now the canvas size is changed based on `window.devicePixelRatio`, one idea is to disable this type fo scaling (see how VS Code's minimap doesn't change when zooming) and then scale manually by applying a multiplier to relevant numbers.

Applies to WebGL and canvas renderers.

**Comment by yoctozepto** [comment]
Just a small comment - this affects HiDPI settting in Windows 10 as well. OTOH, DOM is also affected but looks different (no terminal renderer is able to provide the crispiness of the main editor though :-( ).

**Comment by AddisonG** [comment]
Getting this on Ubuntu 20.04 too. This is with `"window.zoomLevel": -1`

This is the same row, at the start and at the middle of a line. The middle is always blurry.
![image](https://user-images.githubusercontent.com/5109532/94779424-45132a00-040a-11eb-8cf4-3d16cd2388d6.png)

**Comment by carlfriedrich** [comment]
I have cloned the current master and run the demo like [described in the wiki](https://github.com/xtermjs/xterm.js/wiki/Contributing#linux-or-macos). This is how it looks like with Firefox on Windows 10:

![xterm](https://user-images.githubusercontent.com/45259958/151838117-57725947-3c4c-4344-828e-fc7ebcfd97f8.png)

It might seem okay on first sight, but the `OOO` sections are rendered differently depending on the horizontal position in the terminal. This is an enlargement of the three portions:

![ooo](https://user-images.githubusercontent.com/45259958/151838654-021e4af6-ec5c-42b3-904d-32fa6dfc2a28.png)

You can see that the leftmost characters are rendered way more clearly than the ones farther on the right side.

This happens only with the canvas renderer. Switching to the dom renderer leads to much crisper and consistent visualization:

![Animation2](https://user-images.githubusercontent.com/45259958/151839517-ecd68e06-6171-4ae8-a7bb-863689e57ef2.gif)
 
With the dom renderer, the three `OOO` sections appear perfectly identical:

![ooo_dom](https://user-images.githubusercontent.com/45259958/151840692-75bda876-0e55-4dfa-b397-b1ba3af11f50.png)

**Comment by carlfriedrich** [comment]
**Update**: the above observations were taken with a Windows scaling factor of 125%. When I set this to 100%, the canvas renderer is consistent as well:

![canvas renderer on 100% DPI scale](https://user-images.githubusercontent.com/45259958/151843020-92742753-dc17-4118-a7fd-f7023c7aaaa9.png)

So obviously the problem occurs because the canvas renderer does not handle DPI scaling correctly.

**Comment by Tyriar** [comment]
> the above observations were taken with a Windows scaling factor of 125%.

@carlfriedrich good observation, I guess this is just another case of devicePixelRatio not being 1 or 2, so the same issue as window.zoomLevel not being 0.

**Comment by carlfriedrich** [comment]
I took some time to dig into this a bit deeper. @Tyriar Please excuse if I'm repeating what you possibly already know. However, I think this might help other people understand why the issue still exists.

### General observations

1. The issue appears only when zooming is applied to the terminal.
2. It does not matter where the zooming comes from (can be the Windows DPI setting or the browser/parent window, e.g. VS Code).
3. Zooming is a necessary, but not a sufficient condition, i.e. there are cases where the rendering is crisp despite of an applied zoom factor.

The last point was the reason for why it was so hard to make the issue reproducible. I had to research the basics about how the renderer works, so let's take a short tour about:

### The canvas element

Both the Canvas and the WebGL renderer rely on [HTML's `canvas` element](https://www.w3schools.com/html/html5_canvas.asp). This is an area of a webpage which a script can draw content on. Drawing means that the resulting object is a *pixel-based image*. Thus both renderers produce a pixel image of the terminal. This technology has been chosen for [performance reasons](https://code.visualstudio.com/blogs/2017/10/03/terminal-renderer).

### Zooming the canvas element: problem and workaround

When a canvas object is zoomed, it produces aliasing effects, due to the nature of pixel graphics. It's just the same as zooming into a photo.

The xterm.js renderer works around this using the following steps:
- Detect whether a zoom is applied to the page.
- If no:
    - Just draw everything on the canvas normally.
- If yes:
    - Increase the canvas size by the zoom factor.
    - Draw everything on the canvas in the zoomed size.
    - Reduce the canvas to its original (non-zoomed) size.
    - The browser then increases the canvas to the zoomed size again, as it applies the zoom factor to the complete webpage.

Let's use the following symbols to describe the behaviour mathematically:

`w`: canvas width
`z`: zoom factor

The scaled canvas size `w'` is then caluclated as:

`w'` = `w` * `z`

So the terminal is painted on `w'` and then it is visually scaled down, resulting in its original size

`w'` / `z` = `w`

The browser then zooms in:

`w` * `z` = `w'`

i.e. the width that we see is exactly the width that we painted.

### Why the workaround does not guarantee a crisp presentation

In *theory* and in a *continouus scale* the above workaround works great. However, since a screen has a limited number of pixels, we only have a discrete number of possible values for `w` and `w'`, which makes us eventually stumble upon rounding errors.

Let's see two examples:

1. **No rounding error**

    Let's assume a scaling factor of 125% and a canvas width of 100px:

    `w'` = `w` * `z`
    `w'` = 100 * 1.25
    `w'` = 125

    So the terminal is drawn to a 125px wide canvas. Afterwards it is zoomed down:

    `w'` / `z` = `w`
    125 / 1.25 = 100

    So the canvas is included into the HTML document at a width of 100px. Note that internally the canvas still has its drawn size of 125px, we're just displaying it with a reduced width.

    The browser then scales the whole site:

    `w` * `z` = `w'`
    100 * 1.25 = 125

    So in the end the canvas is displayed in the same size it was drawn to, everyhing looks crisp.

2. **Rounding error**

    This time, let's assume the same scaling factor of 125% but a canvas width of 95px:

    `w'` = `w` * `z`
    `w'` = 95 * 1.25
    `w'` = 118.75

    Since the canvas has to have a discrete size, we have to round it:

    `⌊w'⌉` = 119

    In the HTML document, we're styling the canvas with it original width of 95, so:

    `w` = 95

    The browser, however, does not scale each item individually but the complete webpage in one piece. Thus individual items are not rounded to pixel boundaries, only the complete page is. This makes the resulting width of our canvas after the browser zoom in fact:

    `w'` = `w` * `z`
    `w'` = 95 * 1.25
    `w'` = 118.75

    **Result**: We have drawn the terminal to a 119px wide canvas, which is now displayed over the width of 118.75px. So even though we *tried* to make canvas size and resulting display size identical, in fact they are not.

I came across this by analyzing the canvas element in the DOM, where the canvas size and the display size can be directly seen:

```html
<canvas width="119" height="119" style="width: 95px; height: 95px;"></canvas>
```

(Disclaimer: This is an artificial example in order to match my mathematical example above. In the real world I wasn't able to produce these exact sizes with xterm.js, but I had several other combinations of canvas width and style width leading to the same result.)

The issue now gets even more clear when we calculate the zoom factor `z'` between the canvas width and the style width:

`z'` = `w'` / `⌊w'⌉`
`z'` = 119 / 95
`z'` ≈ 1,2526315789 ≠ 1.25

It is obvious that the scaling factor which we actually used to downscale the canvas to its CSS width is not equal to the scaling factor the browser uses to upscale the site.

It's exactly these cases where we're getting the blurry terminal lines. I checked cases without rounding errors (like the 100px and 125% zoom above) and in those cases all characters are displayed equally throughout the whole line.

### Possible solution

We could choose the CSS width `w` in a way that the canvas width `w'` does not have to be rounded. If it has to be rounded, we have to add some padding around the DOM element in order to reduce its size slightly until `w` * `z` is an integer.

This will result in blank spaces around the terminal, the maximum size of which depends on the denominator of the zoom factor `z`.

**Example:**
The zoom factor 125% from the above examples can be written as 5/4, so the denominator is 4. The CSS width then has to be integrally divisible by 4 in order to make the canvas width integer as well.

1. `w` = 100px
    100 is integrally divisible by 4. No adjustments necessary.
2. `w` = 95px
    95 is not integrally divisible by 4. Next lower number is 92 -> difference `d` = 3.

So if we reduce our visual representation of the canvas in the latter example from 95px to 92px and add a 3px wide empty space on one side, we would be able to paint on a canvas of 92px * 1.25 = 115px, which is an integer and thus does not lead to a slightly off zoom factor.

### Drawbacks of the solution

The difference calculated in the above example is the maximum difference that can occur with this given zoom factor, since the next higher number would be 96, which is again integrally divisible by 4.

Generally speaking:

`d max` = `denom(z) - 1`

So with a zoom factor of 125%, the empty border will never be wider than 3px. Personally I would trade off 3px of my monitor for a crisp presentation.

With more sophisticated zoom levels this might get worse, though. If someone sets a zoom level of 101% for example (that would be 101/100 in fractional), we have a denominator of 100, meaning that in the worst case we would add 99px of empty space in order to have a crisp presentation. I'm not sure if this is still a good tradeoff.

### Bottom line

A good compromise might be to define a maximum width of empty space we would accept when aiming for a crisp presentation. If we would have to add more than this maximum, then fall back to the whole width with blurry rendering.
Windows has support for only a limited number of zoom levels:

    125% (=5/4), 150% (=3/2), 175% (=7/4), 200% (=1)

Browsers generally allow any zoom level, but pre-defined values e.g. in Firefox are limited as well:

    30% (=3/10), 50% (=1/2), 67% (=2/3), 80% (=4/5), 90% (=9/10), 110% (=11/10), 125% (=5/4), ...

So perhaps we can agree that we would cover the **vast majority** of use cases by supporting the **above listed zoom levels**. That would mean that the maximum supported denominator would be 10, resulting in a **maximum addition of empty space of 9px**.

I would assume that everybody would trade 9px of their monitor space if the alternative is a blurry font. Still the 9px are not lost, you could resize your terminal accordingly so that other parts around it get more space. However, I am not sure about this (there's always someone to complain ;-)), so we *might* make this a configurable option.

Let me know what you think.

**Comment by carlfriedrich** [comment]
**Addendum**: I don't know if it particularly reproducible in other environments, but in my Firefox running the [xterm.js demo](https://github.com/xtermjs/xterm.js/wiki/Contributing#linux-or-macos) with the default settings (font `Fira Code`, size 15) I get non-rounded values (canvas width: 1320px, display width: 792px) on an overall zoom level of 167% (which is 125% DPI factor and 133% browser zoom). In this setting the font is totally crisp, characters rendered exactly identical throughout the line.
Changing the font type (e.g. to Consolas) or size leads to slightly different canvas and display sizes, resulting in a non-exact zoom factor and therefore a blurry font with characters rendered differently depending on their position.

**Comment by Eugeny** [comment]
IMO trading a few pixels of padding for clear font rendering is a perfectly reasonable thing to do.

**Comment by pasqualirb** [comment]
> We could choose the CSS width w in a way that the canvas width w' does not have to be rounded. If it has to be rounded, we have to add some padding around the DOM element in order to reduce its size slightly until w * z is an integer.

@carlfriedrich Awesome work! Are you preparing a PR?

**Comment by carlfriedrich** [comment]
@pasqualirb Thank you. I'm actually not familiar with the code, I just analyzed the problem to have it reproducible. So I'm hoping for some profound opinion from @Tyriar on this topic.

**Comment by pasqualirb** [comment]
ping @Tyriar

**Comment by Tyriar** [comment]
Sorry about the delay, I haven't reviewed the proposal thoroughly as I'm a bit swamped after a long break from work, but I agree 100% with @Eugeny if it does indeed fix the problem.

> IMO trading a few pixels of padding for clear font rendering is a perfectly reasonable thing to do.

**Comment by carlfriedrich** [comment]
@Tyriar Thanks for your comment. If you like, I can offer to help with the implementation, but I would need some guidance for the code base first.

**Comment by Tyriar** [comment]
@carlfriedrich sure!

Each renderer has a method to calculate the dimensions. Here's the canvas renderer:

https://github.com/Tyriar/xterm.js/blob/cae9f44f5c065d04588ee5ddaa4a7266a70a3b86/src/browser/renderer/Renderer.ts#L195-L206

And webgl renderer:

https://github.com/Tyriar/xterm.js/blob/1e8901630cd38ed4e4c97d32b34d177b948f1b10/addons/xterm-addon-webgl/src/WebglRenderer.ts#L456-L467

I think those are the main places you would need, let me know if you need any other pointers.

**Comment by Tyriar** [comment]
@carlfriedrich thanks a lot for the investigation, I spent quite a while adapting your proposal and it turns out it didn't end up working. However, I did find another solution using a fairly recent web API that wasn't around when the renderers were initially created! https://github.com/xtermjs/xterm.js/pull/3926
