### ISSUE TITLE
add a search bar addon 

### ISSUE THREAD

**Issue by yinshuxun** [xtermjs/xterm.js#2719]
I have a idea to contribute a PR to add search bar addon. 
what do you think  about this idea ?
![image](https://user-images.githubusercontent.com/18656086/74585014-5b06e280-5013-11ea-9995-b4646c264daa.png)
```
# Now in my project, use below code to open the bar
const  searchAddon = new SearchAddon();
const searchBarAddon = new SearchBarAddon({
    searchAddon
  });
 this.terminal.loadAddon(searchBarAddon);
searchBarAddon.show();
```

**Comment by Tyriar** [comment]
The reason the season addon doesn't contribute any UI is because thee UI would need to be tailored specifically for basically every usage and not allow buttons to be moved around. Since creating the UI is relatively simple I think we should avoid doing this sort of thing. By all means create an addon under your user though if you would fine that useful.
