### ISSUE TITLE
Resize/reflow broken 

### ISSUE THREAD

**Issue by gfadlallah** [xtermjs/xterm.js#2744]
![gif](https://user-images.githubusercontent.com/25337748/75606357-9fc55b80-5aa0-11ea-9bc7-76c2f93e4a2f.gif)

Resize is pretty broken, as it doesn't properly wrap text. This is making it difficult to create split panes which are resized often. I've tested this behavior in VSCode and it appears to be an issue there as well. I suspect this may be an inherit problem with the renderer/pty coordination, as I also see this issue (mildly) in both iTerm and the native MacOS terminal.

## Details
- Browser and browser version: Electron 8.0.1
- OS version: MacOS Mojave 10.14.6
- xterm.js version: 4.4.0

### Steps to reproduce

1. Create xterm window hooked up to pty (https://github.com/microsoft/node-pty/tree/master/examples/electron).
2. Use a `resizeObserver` on the top-level container that calls `fitAddon.fit()`, then propagates the rows/cols to pty.
3. Rapidly resize the window.

I've tried debouncing the resize calls, but this doesn't help.

**Comment by Tyriar** [comment]
I've also tested other terminals and seem this as a problem for many of them as well. This happens either as a result of bugs in shells or because resize in xterm.js does not wait on node-pty. The only thing I'm thinking we could do to fix this is to make the resize operation completely synchronous which would be something up to the embedder or xterm.js. So once a UI resize event happens, node-pty gets paused, then node-pty is resized, xterm.js is resized, and then node-pty is resumed.

**Comment by jerch** [comment]
I second what @Tyriar says - and want to add that even with sync resize dispatching we cannot completely avoid those issues, only lower the chance to trigger it. This is due to the simple fact that we cannot control buffering on the slave side of the pty. Also note that xterm.js has a general disadvantage here compared to other emulators due a "long line" from pty to the terminal (we tend to have more buffers involved than a native emulator sitting right on the pty). All those buffers have to be drained/flushed before the actual resize takes place, to fake it as an almost in-band action.

**Comment by gfadlallah** [comment]
@Tyriar @jerch That makes sense. I'm observing a race condition between the pty resize and the xterm resize. We tell pty to resize, and by the time we get data back corresponding to how we should draw the cursor line, the xterm window has already changed size, so the data we obtain is stale. In many cases the ANSI escape sequences we receive from pty on resize cause xterm to write outside of the cursor lines.

My question is: why can't xterm resize the cursor lines itself? If, hypothetically speaking, we had a way to systematically ignore data that came from pty as a result of a resize, then we could just resize pty in the background while xterm handled all the resize logic for all the text.

**Comment by jerch** [comment]
@gfadlallah Yepp, this summarizes the problem behind the curtain.

> My question is: why can't xterm resize the cursor lines itself? If, hypothetically speaking, we had a way to systematically ignore data that came from pty as a result of a resize, then we could just resize pty in the background while xterm handled all the resize logic for all the text.

This wont work either, as we dont know whether the next chunks are a result of SIGWINCH, where the app tries to "repair" the screen state.

Only chance I see is to do the full roundtrip and drain buffers in between:
- terminal gets resized
- pause pty
- drain all buffers
- call pty.resize
  - triggers SIGWINCH
  - app might want to refresh screen state, but pty is still paused (writes are blocking)
- on SIGWINCH
  - do the actual resize in terminal with reflowing
  - resume pty
- next chunks are most likely meant for the new geometry (minus prebuffered data on pty slave, that was written right before pty pause)

This should lower the chance of the race condition by far. Downside of this solution is the implementation overhead (needs several server side adjustments, that are beyond xterm.js control) and the full stop on all interfaces.

**Comment by gfadlallah** [comment]
@jerch Fair enough, thanks for explaining a possible solution. Will try to work around this by simply debouncing the pty resize and creating a UX that mitigates this behavior.

Closing this now, but submitting another sizing bug that I think is unrelated to this behavior.
