### ISSUE TITLE
Loading bars print on multiple lines when they are longer than the terminal width.

### ISSUE THREAD

**Issue by AndrewSverdrup** [xtermjs/xterm.js#2756]
I love Xterm.js, thanks for making an awesome web-based terminal!  I've noticed an issue for a while now but never got around to reporting it. The loading bars print on multiple lines when they are longer than the terminal width. I made a minimal reproduction case here https://codepen.io/AndrewSverdrup/pen/eYNVQzP. More details below, but the CodePen is hopefully pretty self-explanatory.

## Details
- Browser and browser version: Google Chrome, Version 79.0.3945.130 (Official Build) (64-bit)
- OS version: Ubuntu 18.04.3 LTS
- xterm.js version: 4.4.0

### Steps to reproduce

1. Go to https://codepen.io/AndrewSverdrup/pen/eYNVQzP
There are three buttons in the HTML preview above the Xterm.js embed.

- The first button prints a loading bar that fits on one line in the terminal (works as expected).

- The second button prints a loading bar that exceeds the width of the terminal by 2 characters (this shows the bug where the loading bar is printed twice). 

- The third button prints an even longer loading bar to show how the loading bar seems to be printed on a new line for each character that exceeds the width of the terminal.

**Comment by jerch** [comment]
@AndrewSverdrup Your code reprints the whole line for every added character with a leading CR. Thus if your string wrap to the next line, the next CR will place the cursor in front of the second line and start printing from there. Since you reprint the whole line, you see everything "doubled".

Thats not a bug in xterm.js, thats how terminals work. You need to fix that in your logic - either dont reprint everthing with every char, or respect/calc the line wrap (if it wrapped, reprint only that part, not the whole stuff again).
