### ISSUE TITLE
Cursor blinking breaks when using window focus event listener

### ISSUE THREAD

**Issue by Coding-Kiwi** [xtermjs/xterm.js#2764]
I am using xterm inside electron, this bug does not occur inside a normal browser.

My plan was to automatically refocus the terminal when the application is focused again.
If I add the following lines inside the renderer.js the cursor starts blinking wild.

```
window.addEventListener("focus", e => {
    term.focus();
}, false);
```

## Details
- Browser and browser version: electron 8.1.1 chrome  80.0.3987.141
- OS version: win 10.0.17763.1098
- xterm.js version: 4.4.0

### Steps to reproduce

I set up this test if you want to reproduce the issue
```
git clone https://github.com/Coding-Kiwi/xterm-cursor-bug
(cd xterm-cursor-bug)

npm install
npm start
```

when the app launches, the cursor starts blinking faster and two focus events are triggered
the events are logged in the console, both have "global" as their target

**Comment by Coding-Kiwi** [comment]
I fixed it on my side by using the `browser-window-focus` provided by electron instead, but I thought you might want to know this. Also I'm curious why this happens

**Comment by jerch** [comment]
@Coding-Kiwi Yes I can repro it with our demo in chrome 80 under Ubuntu. I think it boils down to this function call: https://github.com/xtermjs/xterm.js/blob/9c19043fed27c5666a58aa110620b5488914bc76/src/browser/renderer/CursorRenderLayer.ts#L366-L370

which does not stop a still running blinking animation for a second focus event (re-focus). Prolly calling `this.pause();` at the beginning will fix that. Or exit early, if the animation calls are already scheduled.

@Tyriar Since I did not write the code, I am not sure which is is better to deal with this edge case.

**Comment by Tyriar** [comment]
I can't repro in either web demo or the linked demo the proposed fix sounds like a good safe thing to do though.

**Comment by Coding-Kiwi** [comment]
Thank you, I'm closing this issue since there is a workaround in my case and an incoming fix in the next version
