### ISSUE TITLE
CoreMouseService uses non-standard naming and dangerous typing

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#2787]
After migrating to eslint we get these errors:

```
/home/daimms/dev/Tyriar/xterm.js/src/common/services/CoreMouseService.ts
   18:3  error  Property name NONE must match one of the following formats: camelCase   @typescript-eslint/naming-convention
   27:3  error  Property name X10 must match one of the following formats: camelCase    @typescript-eslint/naming-convention
   46:3  error  Property name VT200 must match one of the following formats: camelCase  @typescript-eslint/naming-convention
   61:3  error  Property name DRAG must match one of the following formats: camelCase   @typescript-eslint/naming-convention
   76:3  error  Property name ANY must match one of the following formats: camelCase    @typescript-eslint/naming-convention
  126:3  error  Method name DEFAULT must match one of the following formats: camelCase  @typescript-eslint/naming-convention
  142:3  error  Method name SGR must match one of the following formats: camelCase      @typescript-eslint/naming-convention
```

Public methods and properties should be camelCase. Also they are used a little dangerously with `{[key: string]: ICoreMouseProtocol}` as the correct type is actually `{[key: string]: ICoreMouseProtocol | undefined}` (or better yet `Map<string, ICoreMouseProtocol>`) so refactoring it incorrectly could hide some runtime errors.

**Comment by jerch** [comment]
@Tyriar Well the uppercase here results from the idea, to mark them as static data/functions, that are shared between all terminal instances.

> Public methods and properties should be camelCase.

They are not methods, they are just collected in those containers to have a bag for defaults. They are not even exposed to the outside, only handled internally by the service (if you meant that with public). The service itself has getter/setter with explicit `undefined` handling.

> Also they are used a little dangerously with {[key: string]: ICoreMouseProtocol} as the correct type is actually {[key: string]: ICoreMouseProtocol | undefined}

Why do you think the `undefined` is needed here? Imho the opposite is the case, if `undefined` is allowed here, it would defeat the type checking? Those container should never hold a property, thats not of the `ICoreMouseProtocol` type. Thats exactly what it says atm?

**Comment by Tyriar** [comment]
> Well the uppercase here results from the idea, to mark them as static data/functions, that are shared between all terminal instances.

@jerch with uppercase naming, I'm think we should maybe drop that all together as right now it doesn't mean anything and it's confusing as to which one we should be using. Or alternatively add a rule to make their usage more strict if possible. Right now the rule is kind of/sometimes use it for top-level constants/exports of primitives in particular but sometimes objects, not always though. That's why this new rule is so flexible:

```json
{ "selector": "variable", "format": ["camelCase", "UPPER_CASE"] },
```

Where ever we end up landing, I'd like to make this only one format to avoid to inconsistent usage and prevent discussion/thinking about which one is correct as there will only be one correct answer.

In the [@typescript-eslint/naming-convention](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/naming-convention.md) does it says we can't have modifiers for variables so I don't think we can allow this for const only like we used to in tslint:

```json
{"type": "variable", "modifiers": ["const"], "format": ["camelCase", "UPPER_CASE"]}
```

That's the cause of the inconsistency in the codebase though.

> The service itself has getter/setter with explicit undefined handling.

If that's true then we can easily put `ICoreMouseProtocol | undefined` everywhere and then there is no loss of safety. The problem I identified stems from `CoreMouseService.protocols`, `CoreMouseService._encodings` and `DEFAULT_PROTOCOLS` and `DEFAULT_ENCODINGS` potentially have a loss in type safety. I just did this and it finds these potential NPEs:

![image](https://user-images.githubusercontent.com/2193314/77850601-7f182080-7188-11ea-856b-c4b0d2772f0e.png)
![image](https://user-images.githubusercontent.com/2193314/77850609-8808f200-7188-11ea-8469-b415a80040d5.png)
![image](https://user-images.githubusercontent.com/2193314/77850612-90612d00-7188-11ea-8f8e-d3af8b00194d.png)

> Why do you think the undefined is needed here? Imho the opposite is the case, if undefined is allowed here, it would defeat the type checking?

The main problem is due to these 2 lines because TypeScript doesn't return a union type from `Object.keys`.

![image](https://user-images.githubusercontent.com/2193314/77850742-4f1d4d00-7189-11ea-8250-6bed47e29483.png)

Studying the code a little more, I think the right fix is the following:

1. Make the privates a Map since this is not perf critical and it's a nicer/safer type to deal with:
   ```ts
   private _protocols: Map<string, ICoreMouseProtocol> = new Map();
   private _encodings:  Map<string, CoreMouseEncoding> = new Map();
   ```
2. Make `DEFAULT_PROTOCOLS` a `ReadonlyArray<ICoreMouseProtocol & { name: string }>`:
   ```ts
   const DEFAULT_PROTOCOLS: ReadonlyArray<ICoreMouseProtocol & { name: string }> = [
     {
       name: 'NONE',
       events: CoreMouseEventType.NONE,
       restrict: () => false
     },
     ...
   ];
   ```
   Then register like this:
   ```ts
   DEFAULT_PROTOCOLS.forEach(p => this.addProtocol(p.name, p));
   ```
3. Make `addEncoding` and `addProtocol` protected and create a `TestCoreMouseService` that exposes them to the test only. That way we don't need to complicate `ICoreMouseService`.
4. Set array results to constants so we get proper type narrowing after the throw, eg.:
   ```ts
   public set activeProtocol(name: string) {
     const protocol = this._protocols[name];
     if (!protocol) {
       throw new Error(`unknown protocol "${name}"`);
     }
     this._activeProtocol = name;
     this._onProtocolChange.fire(protocol.events);
   }
   ```
5. Tighten up `ICoreMouseProtocol` by making its members `readonly` for even more safety 😄 

> Edit: Just saw your commit - hmm, tbh I dont like syntax rules, that work against the user. By making those names lowercase, it is harder to grasp, what those values mean, while the uppercase names clearly indicate the relation to the enum names. Well, if we change that, we should do it for the enums as well.

The problem with `DEFAULT_ENCODINGS` and `DEFAULT_PROTOCOLS` is that they're properties of an object, not an enum. If we allowed this case then we would have to loosen the names of properties on classes as they're the same thing. For enum members camelCase seems wrong, PascalCase or UPPER_CASE would be better as then it's obvious when you're dealing with an actual enum and not an object.

**Comment by Tyriar** [comment]
@jerch made some changes in https://github.com/xtermjs/xterm.js/pull/2789 would like a review 🙂. This still doesn't touch the naming of the protocols though, and I just noticed that right now we're relying on runtime exceptions instead of compile time checks when setting activeProtocols:

https://github.com/xtermjs/xterm.js/blob/55190fd7035d7451a41361011dae4488797e4e8a/src/InputHandler.ts#L1988-L1990

Possible fix:

Make activeProtocol accept a string enum containing value protocol types, override it in TestCoreMouseService to accept any string just for testing purposed?

**Comment by jerch** [comment]
@Tyriar Regarding the naming I am ok with anything that work for us, as long as it is halfway consistent in the codebase. Its just I am somewhat used to conventions like uppercase for module wide const stuff, or leading underscore for private names from Python. Btw those containers are meant as enums, but since enums dont allow structured content, they ended up as normal static objects. An earlier version even had an additional enum as key provider for them, but that was just a wasteful indirection on top, thus I removed it.

Regarding the `undefined` I cant follow, maybe I miss the point. By adding `| undefined` to the type at declaration level you basically broadened the type to also contain `undefined`. I dont get why you wonder that later code using those definitions will complain now, thats a logic follow-up of your step. If you add `undefined` as allow type, you better handle it everywhere. I did not add it, and since we forbid implicit `undefined` the given arguments in those methods should never be `undefined`, otherwise TS should complain again. You basically introduced the correct type warnings yourself by the broadening. Care to explain what you try to gain here?

> ... I just noticed that right now we're relying on runtime exceptions instead of compile time checks when setting activeProtocols

Yes, thats for a simple reason - the service itself only handles the registering and the processing against `CoreService` of the mouse protocols and encodings, not their definition. The definitions of the default protocols/encodings just happen be declared in the same file, but could come from elsewhere. That separation of concern is also the reason for `addProtocol` and `addEncoding` being public, the definitions are loaded during runtime as protocol/encoding plugins, not statically bound to the instance. I explained the motivation behind doing it this way in https://github.com/xtermjs/xterm.js/pull/2323#issuecomment-513466930. It is also the reason the ident key cannot be an enum type, as it contradicts the extensibility aspect.

**Comment by Tyriar** [comment]
> Regarding the naming I am ok with anything that work for us, as long as it is halfway consistent in the codebase. Its just I am somewhat used to conventions like uppercase for module wide const stuff, or leading underscore for private names from Python.

Let's keep variables uppercase and camel case for now until eslint gives a nice way to more accurately describe what we're after.

> Regarding the undefined I cant follow, maybe I miss the point. By adding | undefined to the type at declaration level you basically broadened the type to also contain undefined.

The safety concerns stem around the fact that these:

https://github.com/xtermjs/xterm.js/blob/55190fd7035d7451a41361011dae4488797e4e8a/src/common/services/CoreMouseService.ts#L168-L169

Mean means that the key could be any `string`, and it would definitely result in an `ICoreMouseProtocol`. For example `this._protocol['doesn't exist']` would result in undefined, but at compile time TS thinks it's an `ICoreMouseProtocol`. This is why I was recommending `Map` as an alternative there, as it's impossible to make this mistake since `Map.get` returns a `T | undefined`.

> Regarding #2789 - I am really sorry, I dont get it. What is the exact hazard you are trying to prevent here? By making addProtocol and addEncoding non public, you dismantled a working interface from my perspective. And the | undefined types introduce type uncertainty. What has been won here? Isn't this worse than before?

That change was about hiding complexity in the service when it's not being used, if there's a plan to expose it then that's a different case.

> (https://github.com/xtermjs/xterm.js/pull/2323#issuecomment-513466930) Still a very exotic use case imho. (Not sure how vscode implements the debug/task output, if its xterm.js based it could easily hook into mouse interactions and do folding etc.)

It seems pretty exotic so I question whether we would ever allow plugging in mouse protocols. FYI debug uses Monaco and tasks are just a special way of launching the terminal so they're xterm.js.

**Comment by jerch** [comment]
> For example this._protocol['doesn't exist'] would result in undefined, but at compile time TS thinks it's an ICoreMouseProtocol. This is why I was recommending Map as an alternative there, as it's impossible to make this mistake since Map.get returns a T | undefined.

But isn't this the case for all mutable interfaces with index access defined (those that are meant to mutate by index access at runtime)? Only way I see to deal with that is using type guards at access level. This way TS can keep doing its static type analysis correctly, as the vulnerable container is behind that "shield". Currently there is no way a new property not being of that type can enter the container (setter), thus the `container[existing_key]` access should always provide that type. For non existing keys there is an additional runtime key check. What might be confusing for you is the handling of the keys, that are proven to be existent (`this._activeProtocol` and `this._activeEncoding`). Yes those could have a narrower type as `keyof`, before doing the direct index access in `triggerMouseEvent`. But thats not really doable with static type analysis for things that mutate at runtime. Instead I extended the shield over those values as well, this way `activeXY` never can hold wrong keys (which is a must have from service API perspective, `activeXY` should always point to a defined encoding/protocol). And defined keys can never hold a wrong type, if added through TS.

To me this is pretty much a false alert ("dangerous typing") and I am under the impression that you are overstretching the type safety TS can give. Yes I could move those containers into its own subclass with certain getters/setters, but what would be different? Those subclasses again would have private code, that has to do the runtime checks, just moving the nasty parts one level down. Also `Map` doesnt give us anything here, beside insisting on "oh, that could be undefined", which is not true with those guards in place (type of Map is broader than needed).

If you still feel uneasy about it, change it. I think all it needs is another type guard around those `_container[_activeXY]` accesses in `triggerMouseEvent`.

> It seems pretty exotic so I question whether we would ever allow plugging in mouse protocols. FYI debug uses Monaco and tasks are just a special way of launching the terminal so they're xterm.js.

Well the discussion about a proper mouse API never took place, thus this implementation is stuck halfway (common/core parts done, browser side still being a mess in `Terminal.ts`). Yet I was under the impression, that some customization is wanted (see @mofux's [comment](https://github.com/xtermjs/xterm.js/pull/2323#issuecomment-514562544)). It is abit weird to re-open that particular discussion long after that partial implementation has landed, and not discussing it in the first place (there are several issues about it, e.g. see #2337 for browser side stuff). I am not against reevaluating things, but please lets not go in circles. I see no need/pressure to make this private/protected for the already private internal codebase, it is even covered by tests. So what?

As you already might have guessed, I feel abit offended by this issue, as it mainly addresses things of my mouse PR, while the discussion during that PR went pretty silent. To summarize this issue and my positions:
- naming conventions changed for non obvious reasons
  My stance here - lets just change either the syntax rules or the names into whatever works best for us and does not break with common conventions.
- unsafe property in access in private code
  My stance - cannot be avoided at all for mutable containers due to the way JS works. TS will always be broken in this regard, unless they introduce runtime checks. Solution: Hide vulnerable access behind internal API with type guards, which is already in place.
- internal public API
  My stance - code is tested and proven to work. It is not exposed to the outside. No need to get the screwdriver again and try to fix things, thats not even broken. We have much bigger harmful loose ends in xtermjs.

**Comment by Tyriar** [comment]
This was just a tiny thing really and is certainly not specific to this file alone. We did a recent refactor in VS Code where we changes instances of `{ {key: T}: V }` to `{ {key: T}: V | undefined }` or `Map<T, V>` and found bugs in the process. That's the "dangerous typing" I was referring to and I've done well over my fair share of this too as it's the pattern we use.

> naming conventions changed for non obvious reasons

tslint has been deprecated several months ago, just moving things forward and trying to tighten up the rules so there's less ambiguity and this instance was the only outlying property using upper case. Let's allow upper case for all properties for cases like this when it's designed like an enum as it's not possible to just target const like we used to with this:

```ts
{"type": "property", "modifiers": ["const"], "format": ["camelCase", "UPPER_CASE"]},
{"type": "variable", "modifiers": ["const"], "format": ["camelCase", "UPPER_CASE"]},
```

---

I certainly didn't mean to offend, I often do these refactor debt PRs I do in my free time to learn more about TS and architecture and to relax. Sorry it came off that way 🙁

I'll probably re-examine the lack of `| undefined` in object later at which point I'll look over the whole codebase and validate that I actually find bug fixes.
