### ISSUE TITLE
Need a API to get the loaded Addons

### ISSUE THREAD

**Issue by ScarlettKK** [xtermjs/xterm.js#2821]
As is known, if we need to load some addons for terminal, we should use the following code:

```javascript
import { Terminal } from 'xterm';
import { FitAddon } from 'xterm-addon-fit';

const terminal = new Terminal();
const fitAddon = new FitAddon();
terminal.loadAddon(fitAddon);
terminal.open(containerElement);
fitAddon.fit();
```
That means we still need the variable `fitAddon` if we want to execute the `fit()` function.

But this is inconvenient when the project is using modularization, we need to export more variables.

Since the `terminal` has already loaded the addon, can we set a `getAddon` API for `terminal`? The using will like this:

```javascript
// terminal.js
import { Terminal } from 'xterm';
import { FitAddon } from 'xterm-addon-fit';

const terminal = new Terminal();
const fitAddon = new FitAddon();
terminal.loadAddon(fitAddon);
terminal.open(containerElement);

export default terminal;

// index.js
import terminal from './terminal';

const fitAddon = terminal.getAddon('fit');
fitAddon.fit();
```

**Comment by Tyriar** [comment]
I'm not really a fan of doing this for these reasons:

- We don't disallow loading an addon twice
- It's not typed well and there is no way I'm aware of that `fitAddon = terminal.getAddon('fit')` would be typed implicitly
- You can just export an `addons` array or `fitAddon` directly

**Comment by ScarlettKK** [comment]
Then how about using `fitAddon = terminal.getFitAddon()`?

> We don't disallow loading an addon twice

The user can get the new addon again.

**Comment by Tyriar** [comment]
@ScarlettKK that wouldn't work either because we can't reference the name of addons in the core API (xterm.d.ts). This was considered when redesigning the types but trying to come up with a way to get addons back really complicated things and was a bit weird as well since you needed to pass the ctor into `getAddon` in order to get the instance of it back, see https://github.com/xtermjs/xterm.js/issues/1128#issuecomment-451362945

I don't think we should do this because of how seemingly complicated this is to do right and there's a very simple workaround on the embedder side (just keep the reference to the addon object).
