### ISSUE TITLE
Excuse me, how to replace the $symbol by default

### ISSUE THREAD

**Issue by bosens-China** [xtermjs/xterm.js#2981]
Not found in the documentation, hope to get your help

**Comment by mofux** [comment]
Do you mean the $ symbol from the shell that usually ends a user prompt? 

I think there is no easy way to do that. There is nothing that tells you where the prompt starts or ends. Also the prompt line may get overwritten multiple times while you are typing, and figuring that out is even harder. Note that xterm.js has no knowledge about the semantics of the content that it is rendering. It only interprets characters and escape sequences and draws them accordingly.

I think the best method here is to change the prompt on the host itself by manipulating the `PS1` environment variable: https://www.cyberciti.biz/tips/howto-linux-unix-bash-shell-setup-prompt.html

Since this is a bug tracker, I would encourage you to take this question over to stack overflow and ask for help there.
