### ISSUE TITLE
textarea position incorrect with custom font size

### ISSUE THREAD

**Issue by terenty-rezman** [xtermjs/xterm.js#3034]
Hidden textarea `xterm-helper-textarea` position computed incorrectly from **js** code when custom font size is used `terminal.setOption("fontSize", 16)`

![image](https://user-images.githubusercontent.com/58115884/89453974-b024e500-d768-11ea-93a7-5c6dbf935800.png)

This makes **the whole xterm view scroll to the right** cutting left edge and exposing unnecessary space on the right, when cursor is close to the right edge. The terminal should also occupy the whole window, I guess, for this to happen.

This is even reproducible on [Hyper](https://hyper.is/):

![image](https://user-images.githubusercontent.com/58115884/89455167-8a98db00-d76a-11ea-8a3e-9f349628e8f5.png)

The easiest way to reproduce is to keep pasting two character string e.g. `"ed"` into the terminal `Ctrl+Shift+V` up to the right border. In fact, the issue only happens when pasting, regular typing won't give the effect.

the `xterm.css` initializes `textarea` width with 0:

```
.xterm .xterm-helper-textarea {
    ...
    width: 0;
    height: 0;
    ...
}
```
but it gets recomputed from **js** later on.

On **vscode** this does not occur though, they probably override `textarea` style in custom way. 

## Details
- Browser and browser version: **Chrome**
- OS version:  **Windows 10**
- xterm.js version: **4.8.1**
- rendererType: **canvas**

### Steps to reproduce

1. Download [Hyper](https://hyper.is/)
2. Keep on pasting (`Ctrl+Shift+V`) "ed" into the terminal

**Comment by kena0ki** [comment]
Currently dimensions of textarea, such as width/height/left/top, is evaluated based on _charSizeService, but they needs to be sync with cursor's ones, which is set in  CursorRenderLayer.

https://github.com/xtermjs/xterm.js/blob/8e151ee6ef8782f59828ca379a5ad5a0e641abd6/src/browser/Terminal.ts#L289-L300

https://github.com/xtermjs/xterm.js/blob/8e151ee6ef8782f59828ca379a5ad5a0e641abd6/src/browser/renderer/CursorRenderLayer.ts#L127

Maybe it is good way that we have dimensions of the cursor set somewhere other components  can see them and we use them for textarea. (IRenderDimensions may be enough though.)

As #3058 is also caused by textarea position, I suppose this fix also resolves that issue.

**Comment by Tyriar** [comment]
I can't seem to reproduce the issue in the xterm.js demo? Could this just be related to Hyper's style overrides?

**Comment by kena0ki** [comment]
@Tyriar 
I can reproduce the issue in the demo by setting `fontSize` to something different than 15.
When size is 15, probably textarea sit right position by chance.

![image](https://user-images.githubusercontent.com/29003390/97662596-db467880-1aba-11eb-873b-ac6963933221.png)

As a side note, when `renderType` is dom, the issue does not happen.

**Comment by kena0ki** [comment]
I created a PR, but didn't unify char size service and renderer calculations.
I thought it isn't needed but If it is, I'll close the PR.  (Because It is too difficult for me to do it without causing regression.)
