### ISSUE TITLE
Get ANSI color information of terminal output in getSelection

### ISSUE THREAD

**Issue by vraddy** [xtermjs/xterm.js#3042]
How to get ANSI color information of terminal output in getSelection (or any other function)

Background: terminal on webpage is piped to ssh via websocket, following is the text received from server via websocket.

`[1;31mOutput from server[m`

this will be written to UI terminal as 'Output from server' in red color.
when i select this text on terminal and use getSelection, get only 'Output from server' as plain text, how to get the ANSI color information which is used to write this line.

**Comment by theflyingape** [comment]
Why getSelection() for this improbable enhancement? The coded sequence from the app is already consumed and rendered in this Xterm emulator by your socket --> term.write().  You are free to capture the raw data yourself within **socket.onmessage** = (ev) => { }

**Comment by theflyingape** [comment]
Back in the day, VT220 terminals had this SETUP feature to echo control sequences as graphic characters instead of interpreting them, useful for debugging. But I don't believe/recall there was a private command to do this programatically.  Perhaps your looking to do the same thing?  See [Display Controls Mode](https://www.vt100.net/docs/vt220-rm/chapter2.html#S2.7) for details on that.
Maybe in your socket, you can convert all ev.data '\x1b' escape characters as '~' before sending it to a term.write() to have the ensuing sequence display?

**Comment by vraddy** [comment]
> Why getSelection() for this improbable enhancement? The coded sequence from the app is already consumed and rendered in this Xterm emulator by your socket --> term.write(). You are free to capture the raw data yourself within **socket.onmessage** = (ev) => { }

Thanks for your response, just wanted to know if there are any function in xtermjs which gives rendered terminal output with ANSI information for selected region. Yes what you suggested is possible solution, i can get the location of terminal selection and map this location to raw data.

Sorry for posting How to question on github(because i didnt get any response on stackoverflow), I will close this.

**Comment by Tyriar** [comment]
`getSelection` will only return text, you can alternatively use the experimental (could change) buffer API:

https://github.com/xtermjs/xterm.js/blob/371c96e1da716f43c70db23c0840cc52bdd0b9c0/typings/xterm.d.ts#L1361-L1401

It's not that straightforward to pull the colors though. Detecting `\x1b` as @theflyingape suggested may be the best way to go.
