### ISSUE TITLE
Select all does not work

### ISSUE THREAD

**Issue by croiuki** [xtermjs/xterm.js#307]
Since 2.0 version, select all in right click menu does not work.
## Details
- Browser and browser version: Google Chrome 50.0.2661.102
- OS version: Windown 7 
- xterm.js version: 2.0.0 / 2.0.1

**Comment by parisk** [comment]
Thanks for reporting @croiuki.

The reason this happens is because the right-click happens now on the textarea instead of the terminal element. Despite that I was not able to use "Select all" on Chrome on macOS even on tag 1.1.3.

A workaround you could use here until we fix this is selecting by dragging your mouse over the area you would like to, while keeping the left-click button pressed.

As I do not ever use "Select all", I would like to know if you would expect it to select all contents in the buffer or all terminal logs. IMO selecting the buffer makes more sense.

**Comment by croiuki** [comment]
Thanks for the reply. 
I just want to select contents more than current screen show, but it also does not work.

**Comment by Tyriar** [comment]
We would need something such as https://github.com/sourcelair/xterm.js/issues/207 to deal with selection beyond the current page. Not sure on whether it can be implemented without causing other issues yet though.

**Comment by Tyriar** [comment]
Select all was implemented in https://github.com/sourcelair/xterm.js/pull/670, it doesn't work with the right click menu but cmd+a will work on macs and a `Terminal.selectAll` API is available for consumers to hook up manually.

**Comment by Tyriar** [comment]
Still an issue in `v3` 
![image](https://user-images.githubusercontent.com/2193314/32460470-bf5c747c-c2e7-11e7-9d7a-f7eacaf5dd58.png)

**Comment by Tyriar** [comment]
I'm not sure there's a way forward on fixing this in the browser, closing off as I don't see a fix but happy to be proven wrong.
