### ISSUE TITLE
Give an option to keep scrollback in alt screen

### ISSUE THREAD

**Issue by zxdong262** [xtermjs/xterm.js#3184]
I know disable scrollback in alt screen do seems clean and less confusing, but still in many terminal apps(like iterm) users can benifit from the scrollbacks, like copy something from prev lines, so have an option could benift some users.

**Comment by mofux** [comment]
Can you give me an example where iterm would allow you scrolling the alt buffer? I can't seem to find such a case. Is there a special setting needed in iterm to get such a behaviour? 

Note that there are some commands like `git log` are rendered in the primary buffer, although they "look" like being rendered in the alt buffer, because they capture mouse scroll events and manually redraw the buffer when scrolling.

**Comment by zxdong262** [comment]
Here is a video to show Iterm scrollback in alt screen, when open vi, keyboard up arrow will trigger scrollback, scroll up with touchpad will show scrollback lines.

https://youtu.be/WVSx4k0SJ-8

**Comment by zxdong262** [comment]
Also cmd + arrow up in Iterm would trigger show scrollback lines too, turns out builtin terminal of mac also support cmd + arrow up to trigger show scrollback lines, but do not support scroll with touchpad

**Comment by mofux** [comment]
Thanks for sharing the video, now I see what you mean. In my case with iTerm2 (Build 3.3.12) it doesn't seem to scroll up to the normal buffer on mouse wheel events, but it does work when using cmd + arrow. It also kinda works in Terminal.app - it jumps up to the previous command line of the normal buffer when using cmd + arrow.

**What iTerm and Terminal.app does**
In their viewport, the alt buffer is always appended to the normal buffer. The alt buffer always has the height of the terminal rows, but with cmd + arrow you can scroll up and down the viewport, which allows to reach back into the normal buffer. Note that mouse wheel events will not scroll the viewport by default when in alt buffer (might be dependant on wether the pty app captures mouse events or not - have not tested). The scrollbar also represents the whole viewport (normal + alt buffer), so you can drag it to scroll up to the normal buffer rows too.

**What xterm.js does**
Our viewport only contains the lines of the active buffer (normal or alt). Changing this behaviour would mean a fundamental change in all our renderers, selection manager, search and linkify addons and many more places. 

Although I do like the behaviour of iTerm and Terminal.app in this regard, I don't see us adopting this feature in the foreseeable future because of the effort it would involve implementing it (and the API surface it will break).

We can still keep this issue open for discussion though.

**Comment by zxdong262** [comment]
@mofux Thank you for the detailed info.
Another thought is if provide an event (onAltScreen) as oppotunity for developers to operate on prev content, maybe can do something similar without big change., not sure if this is possible.

**Comment by mofux** [comment]
@zxdong262 Such an event already exists: `terminal.buffer.onBufferChange` can be used to listen to when the buffer is changed, with the new active buffer (`IBuffer`) being passed as the first argument - see: https://github.com/xtermjs/xterm.js/blob/5cb048094e23da22ccfe46666b87d1ad427dce6d/typings/xterm.d.ts#L1309-L1313

Also `terminal.buffer.active` always holds a reference to the currently active `IBuffer`, and you can check which Buffer type it is via `IBuffer.type`:
https://github.com/xtermjs/xterm.js/blob/5cb048094e23da22ccfe46666b87d1ad427dce6d/typings/xterm.d.ts#L1231-L1238

Is that sufficient?

**Comment by zxdong262** [comment]
@mofux I will do some test, thank you

**Comment by mofux** [comment]
Welcome - if you get this feature working in electerm please let me know, I'm curious to see how you did it 🤓

**Comment by zxdong262** [comment]
@mofux After some tests, confirmed that can do something about it:

Since the app can get all lines of normal buffer when switch to alt buffer, so when user press arrow up+cmd, could just show user the normal buffer lines in another popup or what ever UI element, so user can check the normal buffer content, if try harder, maybe can simulate the UI, make it looks like the other terminal's behavior. As a first step, I would show normal buffer content first.

This is the code, works, but seems a wrong way:

```
term.buffer._onBufferChange._listeners.push(onBufferChange)

function onBufferChange (buf) {
  if (buf.type === 'alt') {
     const normal = term.buffer._normal
     const len = normal.length
     const lines = new Array(len).fill('').map((x, i) => {
        return normal.getLine(i).translateToString(false)
     })
     showLinesWhenUserScrollup(lines)
  }
}

```

**Comment by mofux** [comment]
I thought about this a little bit more and came up with an idea that might work. Every buffer stores the actual lines in an `CircularList` via `buffer.lines`, which is basically a wrapper around an Array that holds the actual lines content. We can replace that list with our own implementation on the alt buffer, and our implementation will concatenate the normal buffer and the alt buffer. Any modifications to the list will be translated back into the original alt buffer list.

Here is a rough JS implementation of it. It's not perfect but could act as a good starting point. Run this code right after you have initialized your terminal:

```javascript

const buffers = term._core.buffers;

// implements the ICircularList interface
// see: src/common/Types.d.ts (line 45)
// see: src/common/CircularList.ts
class CombinedCircularList {

  constructor(altBufferLines) {
    this.altBufferLines = altBufferLines;
  }

  onDelete(cb) {
    return this.altBufferLines.onDelete(({ index, amount }) => {
      cb({ index: buffers._normal.lines.length + index - 1, amount });
    });
  }

  onInsert(cb) {
    return this.altBufferLines.onInsert(({ index, amount }) => {
      cb({ index: buffers._normal.lines.length + index - 1, amount });
    });
  }

  onTrim(cb) {
    return this.altBufferLines.onTrim((amount) => cb(amount));
  }

  get _array() {
    return [...buffers._normal.lines._array, ...this.altBufferLines._array];
  }

  get maxLength() {
    return buffers._normal.lines.maxLength + this.altBufferLines.maxLength;
  }

  set maxLength(newMaxLength) {
    this.altBufferLines.maxLength = newMaxLength;
  }

  get length() {
    return buffers._normal.lines.length + this.altBufferLines.length;
  }

  set length(newLength) {
    this.altBufferLines.length = newLength;
  }

  get(index) {
    return this._array[index];
  }

  set(index, value) {
    this.altBufferLines.set(index - buffers._normal.lines.length - 1, value);
  }

  push(value) {
    this.altBufferLines.push(value);
  }

  recycle() {
    return this.altBufferLines.recycle();
  }

  get isFull() {
    return this.altBufferLines.isFull;
  }

  pop() {
    return this.altBufferLines.pop();
  }

  splice(start, deleteCount, ...items) {
    return this.altBufferLines.splice(start - buffers._normal.lines.length - 1, deleteCount, ...items);
  }

  trimStart(count) {
    return this.altBufferLines.trimStart(count);
  }

  shiftElements(start, count, offset) {
    return this.altBufferLines.shiftElements(start - buffers._normal.lines.length - 1, count, offset);
  }

}

term._core.buffers.onBufferActivate(({ activeBuffer }) => {
  if (activeBuffer === term._core.buffers._alt && activeBuffer.lines instanceof CombinedCircularList === false) {
    const patchedAltBufferLines = new CombinedCircularList(activeBuffer.lines);
    activeBuffer.lines = patchedAltBufferLines;
    activeBuffer._hasScrollback = true;
    activeBuffer.ybase = term._core.buffers._normal.ybase;
    activeBuffer.ydisp = term._core.buffers._normal.ydisp;
  }
});
``` 

With this you can scroll the alt buffer, but only if the mouse is not captured by the program running (I used `vi` to test):

![Kapture 2020-11-27 at 12 30 57](https://user-images.githubusercontent.com/2785983/100444972-9e1ad980-30ac-11eb-91fd-71b97aa18fe7.gif)

Note that this code is using the private API (`term._core`), which might change at any point, even on minor releases.

**Comment by jerch** [comment]
@mofux Wow, thats an interesting hack :exploding_head:. LGTM, just abit worried about two things:
- `ybase` and `ydisp` is normally always 0 for altbuffer, lets hope there is no code that tests for altbuffer beforehand and takes a shortcut in code later on without respecting those values
- :+1: for the the `_array` getter hack, still I wonder how the repeated array copies will behave in perf (high GC?)
