### ISSUE TITLE
Keep the addons published on npm uncompressed/un-uglified

### ISSUE THREAD

**Issue by fengzilong** [xtermjs/xterm.js#3202]
I found the xterm addons published on npm **are all compressed/uglified**
It's **hard to debug** in chrome devtools
Is it better to keep code uncompressed on npm, only do the esnext-to-es5 conversion?
Any thoughts

**Comment by Tyriar** [comment]
It's possible to debug by setting up the addons manually if really needed. I think for most users the convenience of the optimized version is preferred.

**Comment by fengzilong** [comment]
What's the case you mean is more convenient with optimized version? On the CDN? In this case, I think we can provide both optimized and un-optimized versions on CDN like term.js and term.min.js

But on the npm registry, I don't think it brings us any convenience 😥 because user always use a bundler in this scene

**Comment by Tyriar** [comment]
> I don't think it brings us any convenience 😥 because user always use a bundler in this scene

Not always, vscode for example will dynamically import the pre-packaged npm module. The goal is that it should just work without the need for the debugging, it sounds like you're hitting some other bug/problem that should be investigated as part of a dev setup, rather than shipping sources in the npm module.
