### ISSUE TITLE
onSelectionChange() is not fired on rightClickSelectsWord

### ISSUE THREAD

**Issue by marvinthepa** [xtermjs/xterm.js#3216]
Similar as in #3193, a change of selection by using "right click to select" does not trigger onSelectionChange, although the selection changes.

## Details
- Browser and browser version: Chromium 89.0.4372.0
- OS version: Mac OS 11.1
- xterm.js version: master on c669c3fba7

### Steps to reproduce

1. run the [xterm.js demo](https://github.com/xtermjs/xterm.js/wiki/Contributing#running-the-demo)
2. open the developer tools, add a breakpoint:
```javascript
term.onSelectionChange(() => { debugger })
```
3. right click on a word in the terminal -> the word will be selected, but the breakpoint will not be reached.
4. select text the "normal" way by click-dragging -> the breakpoint will be reached

**Comment by Tyriar** [comment]
Nice find.

FYI for a bit of info on the design decisions here since you're digging into this area; the reason the selection code is a bit spread all over the place instead of evaluating the selection in some consolidated function is to avoid creating the selection text every time the selection changes as that may be expensive (eg. ctrl+a, click+drag). This is also why `onSelectionChange` is an `IEvent<void>` rather than an `IEvent<string | undefined>`.
