### ISSUE TITLE
consider adding tags for beta releases

### ISSUE THREAD

**Issue by marvinthepa** [xtermjs/xterm.js#3234]
Tags for beta releases would help investigating issues.

For example, I was trying to investigate a problem I have with emoji that use modifiers (e.g. 🏃‍♀️) on Mac OS Big Sur (might create an issue later).

While part of the problem exists both in the xterm.js demo on master and in vs-code, a part of it does not.
So I wanted to try the demo in exactly the same version that vs-code uses, but vs-code uses 4.10.0-beta.4 - I was not able to find out which revision in this repo this corresponds to.

Please consider tagging the repo for beta releases as well, especially if they are used by vs-code.

**Comment by Tyriar** [comment]
When I set this up I was worried about so many tags, it's so clean right now:

![image](https://user-images.githubusercontent.com/2193314/105903185-6eb51a00-5fd4-11eb-93c2-c075cb8f1c8a.png)

For VS Code specifically, my plan was to add the xterm commit to the change, which I haven't done since 4.7 🤦 https://github.com/microsoft/vscode/commit/3bbf833797b3fc373d1d59da3fc2dfeabe05e5fb

I guess it wouldn't be so bad if there was the extra 20-40 tags per release.

**Comment by marvinthepa** [comment]
I completely understand that you do not want to clutter the tags..

In my very humble personal opinion, I would not mind a lot more tags. I always use the search box in github anyway. In most projects that is way faster than scrolling through the list.

**Comment by Tyriar** [comment]
Fixing this in https://github.com/xtermjs/xterm.js/pull/5143 by addon a `commit` property to published package.jsons so we can directly link published versions to commits in the repo.
