### ISSUE TITLE
Install process assumes node/npm presence

### ISSUE THREAD

**Issue by fake-name** [xtermjs/xterm.js#3268]
Basically, I have a project that doesn't use node at all. 

I'd like to add a clientside browser terminal to the project, but apparently the **only** way to get the distribution JS files is via npm, which I do not have installed and am not interested in cluttering my system up with.

What is the process for a packaged version of xtermjs without the node dependency? Most other js projects generally provide a "dist" package which you can just drop into your www root somewhere.

**Comment by fake-name** [comment]
So, digging around:

 - `npm` provides no way to manually download packages. Because that would make too much sense.
 - `https://registry.npmjs.org/<package>/` can be used to get package metadata. `https://registry.npmjs.org/xterm/`. it provides a 960KB(!) json file.
 - From there, you can manually find the "dist" -> "latest" tag, and then use that to look up the most recent tarball.
 - The subsequent dist tarball then has the assembled `xterm.js` file, confusingly in the `lib` directory rather then `dist`. 

It works, but this isn't exactly a great method for shipping a tool.

**Comment by Tyriar** [comment]
It's not that crazy to assume you have node installed when working with JS as the community has standardized on it as the JS package manager (since Bower was deprecated). If you don't want to install node, there are alternatives like [unpkg](https://unpkg.com/browse/xterm@4.11.0/) where you can get the sources from, run in a Docker container or by using a dev container.

**Comment by fake-name** [comment]
> It's not that crazy to assume you have node installed when working with JS

Incorrect. 

For libraries that have no server side components (`xterm.js` is a decent example here), it *is* crazy to assume you have node installed. 

For example, I have a bunch of python+flask projects with some simple client-side JS. None of them use node. Where I work, we have a bunch of embedded projects which use a C++ server with fairly complex client-side JS, which don't have node installed.

JS is much bigger then node.

**Comment by jerch** [comment]
@fake-name We have chosen npm as distribution channel, because it is convenient for us to do so for several reasons.

You are free to choose, whether you like that or not, and to discuss with us, if there are any better ways, that would also work for us. To get a discussion rolling, it is often a good idea to approach the other side in a friendly, open minded tone and ideally with alternate suggestions or improvements. You basically failed in this regard, which puts you back into a situation, where we dont like to be bother with _your problem_. Thanks for your time.
