### ISSUE TITLE
\u001b[H\u001b[2J Can't clean the screen well

### ISSUE THREAD

**Issue by wenbingzhang** [xtermjs/xterm.js#3331]
## Details
- Browser and browser version: 
- OS version: centos 6.5
- xterm.js version: 4.11.0

### Steps to reproduce

https://user-images.githubusercontent.com/13162606/117746285-c18ea680-b23e-11eb-8cec-bad7b9e3bed8.mov

**Comment by jerch** [comment]
First, there is no right or wrong in how `clear` acts, because different emulators/consoles have established several pattern:
- windows console: would scroll out content until the lower region is empty, preserving all data above. Some emulators have adopted that behavior with a custom setting.
- VT line: would erase last memory page (lower region of terminal buffer). Thats what xterm.js and most other emulators do with default settings.
- xterm: Has extended the ED function (erase in display) with a 3rd variant to also clear scrollback on purpose (`CSI 3 J`). Some clear implementations try to figure out, if the terminal supports this and would fire that sequence as well.

xterm.js supports both the VT line and the extended xterm behavior, for me `clear` also deletes the scrollback under Ubuntu 18.
Why your `clear` implementation does not do this - you either have an outdated `clear` (see its manpage), or your $TERM variable is not set to a terminal type, that supports the extended "E3" capability. Maybe try with `xterm-256color` in $TERM.

**Comment by jerch** [comment]
Then you have most likely an outdated `clear` implementation. centos 6.5 is from 2013, following the history notes on the [manpage](https://man7.org/linux/man-pages/man1/clear.1.html) clearing the scrollback with the E3 setting saw a wider adoption around 2011-2013. Pretty sure your clear does not have that yet. Time to upgrade your distro.

**Comment by wenbingzhang** [comment]
> Then you have most likely an outdated `clear` implementation. centos 6.5 is from 2013, following the history notes on the [manpage](https://man7.org/linux/man-pages/man1/clear.1.html) clearing the scrollback with the E3 setting saw a wider adoption around 2011-2013. Pretty sure your clear does not have that yet. Time to upgrade your distro. Or write your own script alias containing it, something along these lines:
> 
> ```shell
> alias cls="echo -ne '\x1b[3J' && clear"
> ```

Thank you
