### ISSUE TITLE
Resolve perf regression from OptionsService.options

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#3556]
https://github.com/xtermjs/xterm.js/pull/3448#issuecomment-969404249

> This PR creates a significant perf decrease in common modules, which have to ask option service for options (e.g. `Inputhandler.print` alone decreases by ~20%).
> Reason behind: https://github.com/xtermjs/xterm.js/blob/0bc02d6838a2a75048001003617bf172efcf622b/src/common/services/OptionsService.ts#L98-L107
> 
> Fix: dont use getter/setter in fast path code.

We could expose the raw object internally?

**Comment by silamon** [comment]
Hmm, I've spend a lot of time on writing that method, trying to keep it as close to the original code and just to prevent implementing a getter and setter for each existing property of ITerminalOptions. I've looked around and it may be possible to use a Proxy object instead of the code mentioned above. Simple unit test shows that it's about 8-9 times faster than my original implementation. It may be doubled if publicOptions would be removed, which I've already succeeded in a different PR. I'm moving up the constructor only properties check to the Terminal class, which is exposed in public API. I guess performance would be the best though if we implement a concrete class of ITerminalOptions.

**Comment by jaminthorns** [comment]
Sometime over the past few VS Code releases (I can't remember exactly), there's been a pretty noticeable decrease in rendering performance with the integrated terminal. I'm noticing this mostly when scrolling through output that has a lot of background colors (specifically Git diffs in [Delta](https://github.com/dandavison/delta)).

Searching for performance regression issues, I came across this. It seems like the regression was introduced in the neighborhood of when I noticed the performance issues in VS Code's terminal. Before I dig deep and identify exactly which VS Code release introduced this regression, do you think the issue I'm experiencing corresponds to this? I'd just like to have confirmation as a user, and it might be helpful for other users to see if they search or report an issue about integrated terminal performance.

**Comment by Tyriar** [comment]
@jaminthorns can you check your `terminal.integrated.gpuAcceleration` setting?

**Comment by jaminthorns** [comment]
@Tyriar My `terminal.integrated.gpuAcceleration` was unset, so it was defaulting to `auto`. After playing around with that setting while I had an integrated terminal open, I discovered the actual problem, which seems to be with VS Code. I opened a ticket for that here: https://github.com/microsoft/vscode/issues/140128

Looks like this issue is unrelated to my problem.

**Comment by Tyriar** [comment]
@jaminthorns thanks for the report, you spotted a pretty nasty regression 🎉
