### ISSUE TITLE
Don't send ^H when pressing shift+backspace

### ISSUE THREAD

**Issue by tecnobrat** [xtermjs/xterm.js#3759]
I'm not actually sure the purpose of this, but I can't find any other linux-based terminal that currently does this.

Given this diff: https://github.com/xtermjs/xterm.js/blob/f6a384b40198c29f165002b62514015e79f3c7f4/src/common/input/Keyboard.ts#L86-L89

It appears that xterm is explicitly sending a CTRL+h keypress when you press shift+backspace. This causes issues if you want to use CTRL+h for different reasons, such as using it as a mapping to swap tmux panes. It causes the most issues when you're typing things like environment variables and make a mistake so you hit backspace (often without releasing shift) and then tmux (or whatever extra actions you have ctrl+h bound to) gets fired.

It looks like it was added in the very first commit here: https://github.com/Tyriar/xterm.js/commit/8bc844c03d6f93048e27cacd5f84f2dcf09ef4b7

Is there any way I can disable this behaviour or can anyone explain the purpose?

**Comment by Tyriar** [comment]
If it was in the very first commit it's existed for the lifetime of xterm.js from the origin project term.js. I'm very hesitant to change it because of that and since this is the first time I'm hearing problems with it. I'm guessing the reasoning might be because original xterm does it but not sure.

A workaround you can do on your end is to add a custom key event handler and then override the default behavior:

https://github.com/xtermjs/xterm.js/blob/218745ab85fe1b6a6278b64b022302f299ba969c/typings/xterm.d.ts#L883

**Comment by Tyriar** [comment]
The commit history of https://github.com/chjj/term.js/ might give some insight
