### ISSUE TITLE
Ctrl-/ is swallowed 

### ISSUE THREAD

**Issue by mtbar131** [xtermjs/xterm.js#3857]
I am running emacs inside a terminal created with xterm.js ([Tabby](https://github.com/Eugeny/tabby)) and emacs uses `Ctrl-/` for undo. But It seems like xterm.js is swallowing the `Ctrl-/` keypress instead of forwarding it to emacs.

## Details
- Browser and browser version:  Not browser specific.
- OS version: Not OS specific
- xterm.js version: Can be reproduced on latest (as of Jun 12th 2022) master. (commit : 48b8e31794ff218bc724202b037eb0a81de38ca8)

### Steps to reproduce

1. Install emacs on your system.
2. Run xterm.js demo using instructions [explained on the wiki](https://github.com/xtermjs/xterm.js/wiki/Contributing).
3. Start emacs in a non window mode inside the terminal created on the webpage with `emacs -nw`.
4. Type something in emacs and try to undo with `Ctrl-/`. Nothing happens. 

Originally this bug was reported on Tabby repository here: https://github.com/Eugeny/tabby/issues/6235

**Comment by Tyriar** [comment]
I think this is an issue in Tabby

**Comment by mtbar131** [comment]
But if that's the case the why does it repro with the steps I mentioned above?

**Comment by Tyriar** [comment]
It works in VS Code because we define a custom keybinding:

https://github.com/microsoft/vscode/blob/23cbd089edff440353a29c6c373d368b84fa5ff5/src/vs/workbench/contrib/terminal/browser/terminal.contribution.ts#L232-L236

I think I did it like that as ctrl+/ is not mentioned in https://invisible-island.net/xterm/ctlseqs/ctlseqs.html as far as I could tell so I believe it's custom on top of what xterm does.
