### ISSUE TITLE
Resize & fit causing input display incorrectly

### ISSUE THREAD

**Issue by ZodiacWind** [xtermjs/xterm.js#3962]
I used `xterm-addon-fit` to resize the terminal while the window size changing.

The terminal can resize normally. However, if there are multiple lines input,  the current input cannot dispplay correctly:
- If the window becomes larger, many spaces will be added to the tails input instead of filling with following lines.
- If the window shrinks, the current input will be truncated and could not be recovered.

In addition, historical input can be displayed correctly.

![Untitled video——使用Clipchamp制作 (1)](https://user-images.githubusercontent.com/16114897/181673926-e0d1dd03-dd4d-42ea-a2b3-a02c35ab8fc2.gif)
![Untitled video——使用Clipchamp制作 (2)](https://user-images.githubusercontent.com/16114897/181673827-b1a47fa3-03e6-412b-80f5-8cadc77b8bbb.gif)
![Untitled video——使用Clipchamp制作 (3)](https://user-images.githubusercontent.com/16114897/181673842-2acbe756-fdfe-4fa9-9ef5-3b48799bf1ad.gif)

## Details
- Browser and browser version:  Google Chrome 103.0.5060.134（
- OS version:  Windows 11 10.0.25163
- xterm.js version: 4.20 beta 26

### Steps to reproduce

1. Please refer to  the code: https://codesandbox.io/s/xtermreact-demo-forked-o5n04u to reproduce it.

**Comment by Tyriar** [comment]
The resize behavior on Windows is a little special. First there is this option which should be used when using a Windows pty:

https://github.com/xtermjs/xterm.js/blob/a8f63c478cda66001c13dc0ffd660f46d93415f3/typings/xterm.d.ts#L210-L220

This actually disables reflow completely as conpty handles resize instead of the terminal. This is fixed for the most part on recent versions of Windows 11 because of: https://github.com/microsoft/terminal/issues/405

This is how VS Code behaves on Windows 11 21H2 (v22000.795):

![Recording 2022-07-30 at 06 22 19](https://user-images.githubusercontent.com/2193314/181916299-ad32131c-2477-4ede-b839-1732bdb219fe.gif)

VS Code only enables `windowsMode` on Windows < v21376:

https://github.com/microsoft/vscode/blob/e62392c1b91d9e56c2af6257a8f32bd6d0fdf295/src/vs/platform/terminal/node/terminalProcess.ts#L397

I'll add a comment to `windowsMode` about the recommended version.

**Comment by ZodiacWind** [comment]
Thanks for your reply.
