### ISSUE TITLE
Support PowerLine triangle and diagonal line glyphs

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#4258]
VS Code issue showing bad rendering when rendering the glyph from the font: https://github.com/microsoft/vscode/issues/163000

We should support custom rendering of `e0b8` through `e0bf` powerline symbols:

![image](https://user-images.githubusercontent.com/2193314/200959614-86bf5b59-09d6-4367-a444-8bbf9efa6e73.png)

Code pointer:

https://github.com/xtermjs/xterm.js/blob/f381783bd59617d083dabf881ef3270f42502552/src/browser/renderer/shared/CustomGlyphs.ts#L346-L374

**Comment by jerch** [comment]
Wow this is getting tedious, its like writing a custom font for xterm.js in the end. Btw there are more unicode parts, that will need babysitting like that - like the new teletext codepoints for 3x2 blocks.

**Comment by Tyriar** [comment]
We're not covering everything though, just ones that are easy to draw in a canvas. The result is pretty great:

![image](https://user-images.githubusercontent.com/2193314/201133050-993be754-ea61-4ba5-af44-5978a96421f2.png)

> like the new teletext codepoints for 3x2 blocks.

You mean these ones? https://en.wikipedia.org/wiki/Teletext_character_set#Graphics_character_sets

I haven't heard about them before so I don't think we'd bother there. Powerline symbols however are used extensively in a terminal.

**Comment by Tyriar** [comment]
Here's what it looks like when rendered using Cascadia Code PL:

![image](https://user-images.githubusercontent.com/2193314/201143279-52f3b7f6-97ef-4c3b-8ca8-e2f60062d39e.png)

Verified in https://github.com/microsoft/vscode/issues/163000#issuecomment-1309779251 to be `0xE0BE`. We should check a few fonts to make sure they're all single width

**Comment by jerch** [comment]
> You mean these ones? https://en.wikipedia.org/wiki/Teletext_character_set#Graphics_character_sets

Yep. They not commonly used yet, as they got specced pretty recently (like in current or prev unicode version).

**Comment by Tyriar** [comment]
With this I went with single width glyphs, it seems that the original powerline extra symbols used double width but a lot of fonts also use single.

**Comment by jerch** [comment]
@Tyriar Imho the powerline glyph and their correct proportions by fonts using them is just broken (or more diplomatic - underspecced). The fact that most fonts propagate them as single width looks wrong to me, and led to that ugly hack by several prompt scripts with additional SPs after those powerline chars.
I am not sure what the right fix here would be, from a clean spec viewpoint the SP hack is just wrong (in that sense all those prompt scripts are wrong). But they did it because of a lack of proper width spec for that codepoint area. So technically powerline itself is to be blamed for using an under specced codepoint area, and letting fonts/users get away with that sloppy SP hack.

AS I said in some other thread comment (idk where it was) - the PUA region is left unspecced on purpose, if someone wants to fill that gap (powerline does here), they have to provide a proper spec. xterm.js on the other hand would have to load that PUA spec and deal with these codepoints accordingly. Thats how it is intended from unicode side and respected by several other PUA overloads. The SP hack introduced by prompt scripts is wrong and should be banned.

Well it is as it is atm, but this hand-waving state with powerline glyphs will just drop on our feet again and again, until the whole "powerline comunity" will fix the spec and SP issue.

**Comment by Tyriar** [comment]
@jerch there has been very few complaints since we shipped this and prompts look great with the custom rendering. Sure an actual spec would be great but I don't think it's that big of an issue atm. The worst that could happen is they can disable custom glyphs and go back to the terrible regular rendering, or request more fine grained tuning of the custom glyph setting.

**Comment by jerch** [comment]
@Tyriar Sure thing - as long as it works okish - "dont change a running system".

Its just sad, that specs get watered more and more intentionally by ignoring basic ideas. Also not the nerdfont guys are to be blamed here, they clearly state somewhere, that their glyphs are intended as wide (even their font patching generator sets them to wide by default). So basically all font maintainers delivering powerline things as half width override the default setting on purpose. Geez. :sleepy:

**Comment by Tyriar** [comment]
Well both https://github.com/ryanoasis/powerline-extra-symbols and https://github.com/ryanoasis/nerd-fonts show wide, should we change it to wide? It's quite an easy change on our end, at least the rendering of them, changing the actual width of the character might cause some problems?

**Comment by jerch** [comment]
Really can't say which route is better one atm. If we switch to wide by default, we might get issues then from broken prompt scripts always emitting the SP hack. (Or even have to place some sanity code in the renderer to detect that condition and to skip the  superfluous filler SP on purpose).
Idk, maybe lets just stay at the current quirky mode until it causes follow-up issues?
