### ISSUE TITLE
Improve search addon behavior when there are > 1000 results

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#4444]
See https://github.com/microsoft/vscode/issues/178017 for context, `_searchResults` gets set to undefined when there are > 1000 results:

https://github.com/xtermjs/xterm.js/blob/d6599bc0486a5de61eeb86638cf5313f1a91baff/addons/xterm-addon-search/src/SearchAddon.ts#L168-L172

**Comment by ulgyd0gg** [comment]
About the result "0 of -1"

https://github.com/xtermjs/xterm.js/blob/d6599bc0486a5de61eeb86638cf5313f1a91baff/addons/xterm-addon-search/src/SearchAddon.ts#L90-L101

`this._resultIndex` be set to `-1`, when `_searchResults`  already been set to `undefine` because of `_serachResults.size` > 1000 results.

**Comment by jeanp413** [comment]
Created a PR for it https://github.com/xtermjs/xterm.js/pull/4504
