### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'replaceChildren')

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#4602]
From VS Code's error telemetry:

```javascript
TypeError: Cannot read properties of undefined (reading 'replaceChildren')
at g.renderRows in vscode-file://vscode-app/node_modules.asar/xterm/lib/xterm.js:1:81207
at g.handleSelectionChanged in vscode-file://vscode-app/node_modules.asar/xterm/lib/xterm.js:1:79465
at u._renderRows in vscode-file://vscode-app/node_modules.asar/xterm/lib/xterm.js:1:102027
at t.RenderDebouncer._renderCallback in vscode-file://vscode-app/node_modules.asar/xterm/lib/xterm.js:1:99877
at t.RenderDebouncer._innerRefresh in vscode-file://vscode-app/node_modules.asar/xterm/lib/xterm.js:1:20236
at <anonymous> in vscode-file://vscode-app/node_modules.asar/xterm/lib/xterm.js:1:19934
```

https://github.com/microsoft/vscode/issues/188370

**Comment by jerch** [comment]
Geez, this tiny `replaceChildren` change creates alot of fuzz :disappointed:

We prolly should add question marks at the element access here https://github.com/xtermjs/xterm.js/blob/1c98037eede9b6cb9610e20372ec43b6b19e69b7/src/browser/renderer/dom/DomRenderer.ts#L362

and here https://github.com/xtermjs/xterm.js/blob/1c98037eede9b6cb9610e20372ec43b6b19e69b7/src/browser/renderer/dom/DomRenderer.ts#L379

**Comment by Tyriar** [comment]
But how does undefined get into the array to begin with?

https://github.com/xtermjs/xterm.js/blob/1c98037eede9b6cb9610e20372ec43b6b19e69b7/src/browser/renderer/dom/DomRenderer.ts#L248-L252

I don't think that's meant to happen, but if it is then we should change to `private _rowElements: (HTMLElement | undefined)[] = [];`

**Comment by jerch** [comment]
> But how does undefined get into the array to begin with?

Yeah, good question. Both are looping over an elements list, that should not contain nullish values, hmm.

**Comment by jerch** [comment]
Cannot repro the issue in the demo, none of the pretests or reset + input constellations runs into the issue.

On code level at least this looks fishy to me: https://github.com/xtermjs/xterm.js/blob/1c98037eede9b6cb9610e20372ec43b6b19e69b7/src/browser/renderer/dom/DomRenderer.ts#L371

Note the `y <= end` condition - is the index access here 0- or 1-based? Is `end` guaranteed to be always inclusive? Since it does not trigger issues in the demo at all I guess thats well tested - still, could it be that there is a calling code path not correctly limiting `end` here?

**Comment by jerch** [comment]
Looked again into this - could it be an edge case of `renderRows` being called right after a resize, but before `handleResize` did run? Idk if thats even possible from a resize (Is `handleResize` triggered sync or async?), if so, then the reason is clear - `renderRows` gets the bigger buffer grid and `_rowElements` might be short on row elements.

possible fixes:
Either clamp right border to smaller value here, or append missing rows on the fly.
