### ISSUE TITLE
Font not readable in terminal and Firefox

### ISSUE THREAD

**Issue by joysn71** [xtermjs/xterm.js#4746]
On Firefox I experience none readable fonts when `privacy.resistFingerprinting` is set to `true`.

![Screenshot from 2023-09-05 06-57-02](https://github.com/xtermjs/xterm.js/assets/2394633/91b76187-095f-4aed-b9f6-544ce185f4ea)

## Details
- Browser and browser version: Firefox 116.0.3
- OS version: Linux Mint Debian edition 5 (Elsie), based on Debian Bullseye
- xterm.js version: 4.8.1

### Steps to reproduce

1. Open `about:config` page in Firefox
2. verify that `privacy.resistFingerprinting` is set to true
3. Open https://xtermjs.org/

**Comment by Tyriar** [comment]
Yep, that'll happen... Brave also does this but by default which is incredibly annoying. Since this is an advanced feature that you are warned about beforehand I think this is by design as you've explicitly opted to break web APIs.

I'm not opposed to accepting a PR to detect this somehow and throw somewhere provided it doesn't introduce performance problems, but I don't want to keep the issue open as the lib is working as designed.

**Comment by jerch** [comment]
@Tyriar As far as I am aware, this cannot be spotted from JS side at runtime (also would somewhat defeat the purpose of the "scrambling").
