### ISSUE TITLE
No support for xterm Device Status Report control sequence

### ISSUE THREAD

**Issue by stones123456** [xtermjs/xterm.js#4893]
echo -e "\u001b[6n"
the console code is not processed correctly

the xterm Device Status Report control sequence :https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Functions-using-CSI-_-ordered-by-the-final-character_s_

**Comment by jerch** [comment]
CPR (cursor position report) are one of the more often used sequences by cmdline apps. We never got an issue report regarding this before, so maybe "you are holding it wrong"?
Plz provide more context info about your system and how you set up the PTY.

**Comment by stones123456** [comment]
It happens like this. When you run jupyterlab, you browser Jupyter in windows browser, open terminal, run vim,then refresh the terminal,you will find the sequence code like \u001b[2;2R\u001b[>0;279;0c

**Comment by jerch** [comment]
I dont know, what "refresh the terminal" means in your ctx, normally this is not possible w'o heavy lifting on integration side. If its caused by jupyters refresh logic, than there is prolly bug at that end. (Wild guess - they reattach the PTY before replaing the terminal content, which should be the other way around)

**Comment by stones123456** [comment]
OK
Thank you

**Comment by jerch** [comment]
Plz report the issue to https://github.com/jupyterlab/jupyterlab
