### ISSUE TITLE
Mass decoration registration and disposable is slow

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#4911]
VS Code issue: https://github.com/microsoft/vscode/issues/199593

Lots of GC happening when registering and disposing many decorations. Here's an example showing and hiding a command guide in VS Code which creates and then disposed ~16k decorations:

![image](https://github.com/xtermjs/xterm.js/assets/2193314/62943f68-4785-426d-b407-8362732fa5db)
![image](https://github.com/xtermjs/xterm.js/assets/2193314/a51182cd-08c0-4907-aae1-8927780f20dd)

https://github.com/Tyriar/xterm.js/blob/1943636f023b0496c2b95aeb31f2d08d7c0e4dce/src/common/services/DecorationService.ts#L41-L60

Some ideas to speed up:

- Don't use `splice`(!) in `SortedList`
  - Doing something more clever here would probably vastly improve registration
- Use an object pool
- Defer clean up to idle callback

**Comment by jerch** [comment]
My guess also goes to the splice needs here, `SortedList` basically implements the insert sort idea, which is nice for insertion/removal at the end with _O(1)_, but soon saturates to _O(n²)_ for average (I guess this happens alot here, when lines drop off the scroll buffer).

**Comment by Tyriar** [comment]
Yes RB or AVL is probably the fix. I've done both before but it looks like I never bothered porting the RB tree from js to ts yet. https://github.com/gwtw/ts-avl-tree, https://github.com/gwtw/js-data-structures/blob/master/lib/red-black-tree.js

> A balanced tree based impl will perform alot worse for typical insertion/removal at the end. Maybe partitioning of the list (like a skiplist) will already do the job here?

It's still just log n though, the main thing that matters is that it scales well imo

**Comment by tisilent** [comment]
I see if there is anything I can do on the demo to facilitate subsequent verification. 😀

**Comment by jerch** [comment]
@Tyriar How would an easy repro look like? Is it enough to spam tons of decorations all over the lines, or do they need to follow a certain pattern?

Which action triggered the toxic removals? Was that just from scrolling off at the top? Because if thats the case, we could prolly lift some burden here by batching the removals with interim "dead keys" on the sorted list and doing a final cleanup copy. Difference would be _O(n log n)_ vs. currently _O(n*m log n)_ for _m_ elements to be removed from _n_ elements (the _m_ multiplier comes from the splice copy overhead for every single removal in our current bisearch&splice approach).

**Comment by Tyriar** [comment]
There's a lot of decorations in vscode now with shell integration, especially when you're hovering the terminal as there's a "command guide" as well:

![image](https://github.com/xtermjs/xterm.js/assets/2193314/bdc040d4-fd4b-4deb-9cea-5c7eebf1408e)

I think my repro above was something like running `tree` and then scrolling up with smooth scroll on. Doing a find will make it more intense

**Comment by Tyriar** [comment]
Example with the decoration stress test button I made:

![image](https://github.com/xtermjs/xterm.js/assets/2193314/e24e589e-e58f-48b9-bc9b-e2da5e37dcb2)
