### ISSUE TITLE
The website uses HTTP instead of HTTPS by default

### ISSUE THREAD

**Issue by SuleymanCommits** [xtermjs/xterm.js#5118]
When I click on the site on Google it uses HTTP by default even though replacing it with HTTPS manually works. I'm on the latest version of Firefox if that matters.

**Comment by jerch** [comment]
Context is often very important, esp. if you want others to understand your issue:
- What are you talking about?
- Which site are you referring to?
- What does this site have to do with a terminal emulator?
- How does not using HTTPS make it looking bad?

And if you are interested, I also have a few random remarks on common HTTPS misconceptions:
- Not using HTTPS does not make a website insecure per se. If a browser states it like that, it is wrong.
- Not every website needs HTTPS, esp. smaller pure informational sites dont need it.
- HTTPS does not come for free, its encryption is a major cost factor for servers and creates high power consumption.

I know that google lobbies for HTTPS for years now, but plz dont follow it blindly. Use encryption where it is useful and actually secures something. For everything else it is waste of resources.
(Mind you - the fact that google lobbies for HTTPS that much, while also preventing proper end-to-end email encryption, speaks for itself...)

**Comment by SuleymanCommits** [comment]
> Context is often very important, esp. if you want others to understand your issue:
> - What are you talking about?
> - Which site are you referring to?
> - What does this site have to do with a terminal emulator?
> - How does not using HTTPS make it looking bad?
> 
> And if you are interested, I also have a few random remarks on common HTTPS misconceptions:
> - Not using HTTPS does not make a website insecure per se. If a browser states it like that, it is wrong.
> - Not every website needs HTTPS, esp. smaller pure informational sites dont need it.
> - HTTPS does not come for free, its encryption is a major cost factor for servers and creates high power consumption.
> 
> I know that google lobbies for HTTPS for years now, but plz dont follow it blindly. Use encryption where it is useful and actually secures something. For everything else it is waste of resources.
> (Mind you - the fact that google lobbies for HTTPS that much, while also preventing proper end-to-end email encryption, speaks for itself...)

I think it's pretty obvious what I'm talking. I'm referring to the site of the repo the issue is in, aka xtermjs.org. I think it's pretty obvious what the site has to do with the repo. Not using HTTPS makes it look bad because browsers make it seem that way. I know that HTTP isn't inherently insecure, especially since there's no real data transfer, but it's still not a good look for people who don't know as much. HTTPS is free if you use Let's Encrypt and I highly doubt the claim that it consumes power, source on that please. And I think it's pretty clear why Gmail isn't E2E encrypted seeing as they want to introduce features like AI responses.

**Comment by SuleymanCommits** [comment]
it takes literally one line to fix so I don't know why you're being pedantic

**Comment by jerch** [comment]
Sorry, we get all sorts of weird issue report from peeps, so it was not obvious to me, that you are referring to xtermjs.org.

For me it opens the HTTPS version automatically in chrome and firefox, but I can force it to use HTTP only by removing the "s", thus HSTS is prolly not set. The website is on github.io, idk if it allows us to change that setting.

Well xtermjs.org is one of those sites, which does not win anything with HTTPS, it does not deal with sensitive data by any means, as it is just an nicer way to present API docs. Dont get me wrong, we actually take security very serious (see https://xtermjs.org/docs/guides/security/), but a false flag is still a false flag. And ppl scared away by that are prolly not the right audience to tamper with a terminal in HTML, if they cannot differenciate in basic security aspects.

> ... I highly doubt the claim that it consumes power...

What? Ofc it drains power, nothing comes for free in computing, esp. if it involves complex math equations. You can test that yourself - do a load test in HTTP and HTTPS on an otherwise resting machine and you will see differences in latency, throughput (or requests/s) and overall system load. Which means admins have to scale to more or bigger machines earlier. Since AES-NI it is not as bad as it used to be, but that trades an almost restored throughput with higher power consumption of the additional silicone. On mobile devices/IoT the encryption stack is a major reason for battery drain.

> source on that please.

Dude this is not twitter, if you dont know about it, it is not my responsibility to educate you. Ah whatever:
- https://eprints.soton.ac.uk/469889/1/Comparative_Analysis_of_Energy_Costs_of_Asymmetric_vs_Symmetric_Encryption_Based_Security_Applications.pdf
- http://www.sce.carleton.ca/faculty/huang/iccae-2020.pdf

**Comment by SuleymanCommits** [comment]
huh that's weird, it does use HTTPS by default on Chromium but not FF. Maybe I messed something up

**Comment by Tyriar** [comment]
Thanks for pointing it out, I flipped the switch to enforce https:

![image](https://github.com/user-attachments/assets/1d9f92f2-b6f0-43df-b84c-cf65308665e0)

It might need another change to land before that is enforced but it should happen at some point soon.
