### ISSUE TITLE
Theme cursor alpha is being ignored for GPU renderer

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#5241]
Repro in VS Code:

```js
"workbench.colorCustomizations": {
    "terminalCursor.foreground": "#ffffff25",
  }
```

GPU:

![Image](https://github.com/user-attachments/assets/038ceec5-df0b-4b8c-a29a-29e5cbd13f5c)

DOM:

![Image](https://github.com/user-attachments/assets/d2492bd9-fe4e-4883-b7de-630a6c1bb018)

**Comment by AnouarTouati** [comment]
The whole thing is built on 32 bit, so the alpha in RGBA is being truncated to allow space for flags that indicate which color system to use (RGB,P16,P256). In hex it looks like this FF-RR-GG-BB (F here is for flag).
I modified the code to try and make it not truncate the alpha channel when the cursor is being drawn. But, that introduces artifacts because other parts of the code relay on the same format.
I think the solution is to move all colors to 64 bit with the following format FF-RR-GG-BB-AA (F for Flag) which is a total of 40 bits.

**Comment by Tyriar** [comment]
@AnouarTouati I think we're using the maximum number of bits that can reliably be used in a JS number across engines. The solution I'd go with here is when an alpha value is used, when the theme is being set to blend the cursor color with the background color here:

https://github.com/xtermjs/xterm.js/blob/e826f6b69f42a2b0c5a3a532300db58be70b50e9/src/browser/services/ThemeService.ts#L81-L91

**Comment by Tyriar** [comment]
Changing `cursorAccent` too in https://github.com/xtermjs/xterm.js/pull/5262, this changes behavior of the DOM renderer a little as it's no longer blending with whatever color is underneath. Instead it blends ahead of time only against the background color so it's a fixed color.
