### ISSUE TITLE
Vim gets confused

### ISSUE THREAD

**Issue by BenHall** [xtermjs/xterm.js#546]
Reproduce in Chrome:
- Load https://www.katacoda.com/courses/docker/3
- Run the command `vim app.js`
- Unable to navigate around the file using Vim.
- Sometimes Vim displays lines in a random/part displayed way

I believe this is related to the terminal lines disappearing bug (#385) that was fixed in 2.3.1

**Comment by Tyriar** [comment]
Some questions:

- How are you talking to the backing pty?
- Are communications guaranteed to land in xterm.js in the order in which they are fired by the pty?
- Is this a new error in 2.3 (or 2.3.1)?

**Comment by BenHall** [comment]
- Websocket goes directly to Docker's API
- I'm not sure, I don't do anything to change it, at least I don't believe
- Kind of. Previously it caused Javascript errors, related to #385. This would result in strange Vim behaviour.

**Comment by Tyriar** [comment]
It seems to work fine when you resize the browser, are you on 2.3.2?

Something funny is going on since the last row contains both vim's footer and the output, that's what's causing the problem:

![image](https://cloud.githubusercontent.com/assets/2193314/22996934/5eb80dca-f385-11e6-9782-b675dbada6be.png)

After a resize:

![image](https://cloud.githubusercontent.com/assets/2193314/22996946/6c72a236-f385-11e6-9ac5-2d06d9cd2bc2.png)

**Comment by BenHall** [comment]
Ah, good spot. Yes, it's 2.3.2

**Comment by Tyriar** [comment]
I think this is fixed
