### ISSUE TITLE
attach addon and xterm.destroy

### ISSUE THREAD

**Issue by ficristo** [xtermjs/xterm.js#663]
I'm using the attach addon with xterm.
When I call xterm.destroy I would expect that the underlying socket is closed and the server socket connection receive a close event.
I added an explicit `term.socket.close();` before calling `term.destroy();`.
Is it correct? If not, what is the right thing to do?

## Details
- Browser and browser version: -
- OS version: -
- xterm.js version: 2.6.0

**Comment by parisk** [comment]
That's an interesting scenario, that actually I have never thought about 😅 .

The way I can see this working right now is by adding an `autoCloseSocket` argument in the `attach` method that defaults to `false`, in order to avoid breaking the current API.

I think the most rational way to go is closing it on destroy by default, which can be the case in xterm.js 3.0.

**Comment by Tyriar** [comment]
@jerch would this be as easy as adding `this._socket.close()` below this line?

https://github.com/xtermjs/xterm.js/blob/43b291112e4becd22e10d1c71967cfecc321f7b1/addons/xterm-addon-attach/src/AttachAddon.ts#L43

**Comment by jerch** [comment]
Hmm not sure if we should do this: Imho we would violate a basic ownership rule, since the socket instance comes from outside.

Not sure why the addon loads attaches to an existing websocket, my guess is that it might be used for other things as well? Otherwise we could create the socket within the addon and free it on dispose.

Also we could keep it as it is and give the addon ctor an option to indicate, whether the socket shall be closed on dispose.

**Comment by Tyriar** [comment]
Makes sense, I say let's keep it as is then (since the socket is initialized outside, it should be disposed of outside).
