### ISSUE TITLE
Violation warning about touch and wheel event listeners not being passive

### ISSUE THREAD

**Issue by parisk** [xtermjs/xterm.js#829]
It seems that Chrome does not like that we do not use passive event listeners for touch and wheel events.

More information on passive event listeners:

- https://developers.google.com/web/updates/2016/06/passive-event-listeners
- https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md
- https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Improving_scrolling_performance_with_passive_listeners

## Details
- Browser and browser version: Chrome 59
- OS version: macOS Sierra
- xterm.js version: 2.8.1

### Steps to reproduce

1. Open demo
2. Open console to view logs

### Screenshot
![image](https://user-images.githubusercontent.com/1188592/28863572-2aacf114-7772-11e7-8e98-09ff9116b4e0.png)

**Comment by Tyriar** [comment]
Do we just need to mark it as `{ passive: false }` as we need to cancel the scroll currently?

**Comment by mofux** [comment]
@Tyriar I think that is what needs to be done, yes. I believe it is only warning because we have not explicitly told the handler how to behave.

**Comment by Tyriar** [comment]
I can't seem to get the warning in my console so this is tough for me to repro, I have definitely seen it before though.

**Comment by mofux** [comment]
As far as I can see we never prevent the scroll event, which means we should be able to safely register it as a passive handler via `{ passive: true }`.

**Comment by Tyriar** [comment]
This one's driving me crazy, I don't want to fix it unless I can actually reproduce the warning but can't seem to on any of my machines 😕

**Comment by nikonso** [comment]
@Tyriar, @mofux 

Hey, I manged to repro the warning on my machine, but while trying to fix it, I came to the conclusion that we can't mark them all as passive because of this block of code, where we're preventing page scrolling.

https://github.com/xtermjs/xterm.js/blob/a8964a15ddf8d2e09aca51cf29b0f83440ef5ea2/src/Viewport.ts#L125-L127

![image](https://user-images.githubusercontent.com/16099035/41005747-a5d49e46-6916-11e8-9722-06af55e9ac24.png)

What should I do, ignore this one and mark the others as passive, do we ignore this issue, or a third option maybe?

**Comment by Tyriar** [comment]
@nikonso yes we want to explicitly say that they are *not* passive, that will go away with the warning as we're telling the browser that we know about the risks.
