### ISSUE TITLE
Lazy load BellSound using TS dynamic imports

### ISSUE THREAD

**Issue by Tyriar** [xtermjs/xterm.js#894]
After https://github.com/sourcelair/xterm.js/pull/878 BellSound will be loaded in before the Terminal is initialized, delaying the time it takes and increasing the memory even when no bell is desired.

See https://github.com/Microsoft/TypeScript/issues/12364

**Comment by mofux** [comment]
If lazy import is not an option, couldn't we load it similar to the way we load addons currently?

**Comment by Tyriar** [comment]
The addon loading logic is so messy imo, hopefully we can get away without doing something like that.

**Comment by mofux** [comment]
Yeah... I think the problem is that there are all these different loaders we have to support. Would be nice to have an abstraction for those, so we could simply import resources lazily. Mmmmpf... that's the part of modern javascript that really sucks - I hope this problem will be solved once the official html module api has settled. Anyway, I don't really see a way of loading the bell audio lazily without it. Even if we get the dynamic imports to work it will depend on the loader (e.g. webpack) to support it.

**Comment by Tyriar** [comment]
Using dynamic imports in a library is a bit of a mess, I don't think we should do this. The current situation is decent.
